### ISSUE TITLE
Viewing overlays on surface view

### ISSUE THREAD

**Issue by spiropan** [rii-mango/Papaya#102]
Hello,
I am able to load surface files by i.e. converting Freesurfer surface file to gifti "mris_convert lh.pial lh.pial.gii". 

However, I'm not clear how to view overlays on top of the surface view. My overlay looks fine on the image volumes, but it is not appearing on the surface. Is there an additional step I am missing?
Many thanks in advance!

**Comment by martinezmj** [comment]
It won't dynamically paint the overlays on to the surface.  For now, you need to create a surface file that contains RGBA data with the overlays already painted onto it.  One tool you can use to do this is Mango: either saving the data via the surface viewer File menu or using the Image > Create Webpage tool to output Papaya with the data.

I'd like for it to support painting the overlays automatically one day.

**Comment by spiropan** [comment]
Thanks I'll check out Mango. I've been looking into it and so far haven't
found a way to use any freesurfer tools to "merge" scalar data with the
surface files. Do you happen to know what other programs read and use
surface files with RGBA data? If so I can look into those to see if they
might have any command line tools that read and manipulate freesurfer
files..

**Comment by martinezmj** [comment]
I've never been sure if including the RGBA data in the GIFTI file is the "official" right way to do it.  If I remember correctly, FreeSurfer ignores it -- it has its own color format.  I also know GIFTI support a separate RGBA format -- it might be worth adding support for that in Papaya.

Sorry, I don't know of any other software other than FreeSurfer and Mango for working with GIFTI surface files.
