### ISSUE TITLE
World coordinate not base on ImagePosition

### ISSUE THREAD

**Issue by fancyoung** [rii-mango/Papaya#103]
In a chest DICOM, the ImagePosition is `-100,-100,100`, the top-left coordinate is `-100,100,100`.

There are two problem: 
1. X. Some dicom LEFT and RIGHT are opposite, and papaya switch them back. But I find other mpr tools still inherit original view, LEFT and RIGHT are opposite.

2. Y. The world coordinate from top to bottom should be increase, but papaya toggle the sign, so the World coordinate(xyz shows in bottom) isn't base on ImagePosition.

It's a bug or on purpose, why?

**Comment by martinezmj** [comment]
1. Do you mean radiological vs neurological view?  If so, there is a "Radiological Display" setting in Settings.  You can also control this via the 'radiological' parameter: https://github.com/rii-mango/Papaya/wiki/Configuration#display-parameters
 
2. Not sure how to solve this one.  The relevant functions are `papaya.volume.dicom.HeaderDICOM.prototype.getBestTransform()` and `papaya.volume.dicom.HeaderDICOM.prototype.getOrigin()`.  In general, the answer would be in src/js/volume/dicom/header-dicom.js.  If you can identify a bug, please let me know.
