### ISSUE TITLE
Change Image Options for DICOM volume

### ISSUE THREAD

**Issue by stergioc** [rii-mango/Papaya#105]
Hello everybody,

I wonder if there is a solution to one of the problems I encounter. I am building a web app where papaya is populated by dicom files that are retrieved from a DICOM server using wado requests. In order for the user to select the study/series to be loaded, I have implemented a simple explorer (Similar to #76). When the user selects some series, I compile an array of urls and use these to load the series in papaya using the following script:

```javascript
var params = [];
params["images"] = [[ 'image1-url', 'image2-url' , 'image3-url', ... ]];
papaya.Container.resetViewer(0, params);
```

I want to change the display range of the viewer to a predefined fixed range, for each series I load. This is because some dicom files have wrong headers and I am mostly using only one kind of images (Similar to #87). In the Configuration wiki page I found that this can be done by passing the min and max values to the `params` like that:

```javascript
params["myOverlayImage.nii.gz"] = {"min": 4, "max": 8, "lut": "Red Overlay"};
```
however I cannot see how this can be applied when you have a series of .dcm images instead of nifti images.

**Comment by martinezmj** [comment]
For a DICOM series you can use the series description or if that's not available the series UID.  Whatever appears in toolbar title area.  For example, you can edit tests/debug_server.html with the following which uses the included DICOM example study:

  ```
var params = [];
params["images"] = [["data/dicom/brain_001.dcm", "data/dicom/brain_002.dcm", "data/dicom/brain_003.dcm", "data/dicom/brain_004.dcm", "data/dicom/brain_005.dcm", "data/dicom/brain_006.dcm","data/dicom/brain_007.dcm", "data/dicom/brain_008.dcm", "data/dicom/brain_009.dcm","data/dicom/brain_010.dcm", "data/dicom/brain_011.dcm", "data/dicom/brain_012.dcm", "data/dicom/brain_013.dcm", "data/dicom/brain_014.dcm", "data/dicom/brain_015.dcm","data/dicom/brain_016.dcm", "data/dicom/brain_017.dcm", "data/dicom/brain_018.dcm","data/dicom/brain_019.dcm", "data/dicom/brain_020.dcm"]];

params["FSE PD AXIAL OBL"] = {min: 200.0, max: 900.0};
```

In this example, "FSE PD AXIAL OBL" is the series description.

**Comment by stergioc** [comment]
Hey @martinezmj,

that worked like a charm. Thanks a lot.
