### ISSUE TITLE
How to use the data returned by WADO?

### ISSUE THREAD

**Issue by ztq0924** [rii-mango/Papaya#106]
![image](https://user-images.githubusercontent.com/20768697/33813759-d691293c-de60-11e7-8a3b-4f83edea7443.png)

**Comment by martinezmj** [comment]
If the URL returns a DICOM, then you should be able to use Papaya in the standard way, specifying your URLs like so, without using XMLHttpRequest:

```
params["images"] = [["my/series/001.dcm","my/series/002.dcm","my/series/003.dcm"]];
```

If you're sure you want to use raw data, see this example: https://github.com/rii-mango/Papaya/blob/master/tests/debug_server_arraybuffer.html

```
        function handleFileSelect(evt) {
            var file = evt.target.files[0];
            var reader = new FileReader();
            reader.onload = function() {
                var params = [];
                fileData = reader.result;
                params["binaryImages"] = ["fileData"];
                papaya.Container.resetViewer(0, params);
            };
            // Read in the image file as a data URL.
            reader.readAsArrayBuffer(file);
        }
```

See the Wiki for more documentation: https://github.com/rii-mango/Papaya/wiki/Configuration#images

**Comment by ztq0924** [comment]
Thanks very much for your answer. 
When i use the URL returns a DICOM,the browser is displayed as follows
![image](https://user-images.githubusercontent.com/20768697/33815204-a53af700-de6a-11e7-9984-2d24c4497949.png)
If i use raw data,browser error
![image](https://user-images.githubusercontent.com/20768697/33815396-fcd53812-de6b-11e7-92d6-6fc5353d309d.png)

**Comment by martinezmj** [comment]
It looks like you are loading multiple URLs.  If these are part of the same series, then you need to group them as an array within the params array.  

```
[["my/series/001.dcm","my/series/002.dcm","my/series/003.dcm"]]
```

If instead you group the like this:
```
["my/series/001.dcm","my/series/002.dcm","my/series/003.dcm"]
```

Then it will interpret this as a list of different series and attempt to overlay them, in which case there is a limit of 8 (but this can easily be changed if necessary).
