### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by XUXUSSS** [rii-mango/Papaya#108]
Hi papaya developer,

We are using params `(e.g. params["images"] = ["data/myBaseImage.nii.gz"];)` to load local DICOM series, but website browser (Firefox) reported error “out of memory” when loading DICOM series with big size (in our situation, the size of one DICOM series is 2M*420 = 840 M). However, this big DICOM series can be opened and displayed correctly in the provided papaya demo (“select file” mode). Any idea about this issue? Thank you very much!

**Comment by martinezmj** [comment]
My guess is that the error is misleading and what is really happening is that it's not reading the header correctly for some reason.  It might be reading the size of a something wrong and then trying to allocate some outrageous amount of memory for it.

I don't have an explanation for why it works with local reading vs web.  If you can recreate this, is it possible to share a file to test with?
