### ISSUE TITLE
"No Pixel Found" Error

### ISSUE THREAD

**Issue by sumancavisson** [rii-mango/Papaya#109]
Hi,
When i trying to dynamically load the dicom/nfti image through Ajax call, it is not rendering - it gives error in console "No Pixel Data Found" while integrated with spring boot framework But it is running fine in tomcat(locally).

There are some extra response header is coming in case of spring boot,XX-params which block for rendering for spring security
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-XSS-Protection:1; mode=block
I also tried for customize header and remove the X -content  and tried then also it does not work for me.

Can you please help why this error is giving in spring boot frame work?

I get the following error:
papaya.js:2833 Error: No pixel data found!
    at papaya.volume.dicom.HeaderDICOM.readNextHeaderData (papaya.js:2760)
    at papaya.volume.dicom.HeaderDICOM.readHeaderData (papaya.js:2759)
    at papaya.volume.Header.readHeaderData (papaya.js:2690)
    at papaya.volume.Volume.finishedReadData (papaya.js:2832)
    at papaya.js:2831

Below is my code :
function loadImageViwer()
    {
    	var params = [];
    	params["images"] = [$('#contextPath').val() + 'secure-rest/emr/getFile'];
		papaya.Container.addViewer("papayaDiv", params);
		papaya.Container.startPapaya();		
    }
Same code is working locally as well as tomcat.

Please help me out. 
Thanks in advance.

![11](https://user-images.githubusercontent.com/16671057/34680168-45d86a76-f4be-11e7-9e79-8eb5592fe812.PNG)

**Comment by martinezmj** [comment]
Are you sure the image has pixel data in it?  Not all DICOM images contain pixel data.  That error would be thrown if it could not find the pixel data tag (7FE0, 0010) in the header.

**Comment by sumancavisson** [comment]
Hey Michael,
 May be you are right but i am able to fix this by set response header. 
There was some missing header because of spring security.
I just added this following line and it worked for me.
response.setHeader("Content-Disposition", "inline; filename=\"" + name + "\"");
