### ISSUE TITLE
Cannot set property 'bowser' of undefined

### ISSUE THREAD

**Issue by hu3402379** [rii-mango/Papaya#112]
Hi, i  use vue-cli, and import papaya from './papaya.js', when I run 'npm run dev', the console print error 'Cannot set property 'bowser' of undefined'.

**Comment by hu3402379** [comment]
when i use  import papaya from './papaya.js' or  var papaya = require('./papaya.js') . and then I print papaya object in console, it likes this:
 `DataArray
:
ƒ ()
GIFTI
:
ƒ ()
ImageDimensions
:
ƒ (p,b,e,m)
TAG_DATA
:
"Data"
TAG_DATAARRAY
:
"DataArray"
TAG_DATASPACE
:
"DataSpace"
TAG_GIFTI
:
"GIFTI"
TAG_LABEL
:
"Label"
TAG_LABELTABLE
:
"LabelTable"
TAG_MATRIXDATA
:
"MatrixData"
TAG_MD
:
"MD"
TAG_METADATA
:
"MetaData"
TAG_NAME
:
"Name"
TAG_TRANSFORM
:
"CoordinateSystemTransformMatrix"
TAG_TRANSFORMEDSPACE
:
"TransformedSpace"
TAG_VALUE
:
"Value"
Transform
:
ƒ ()
Utils
:
{crcTable: null, makeCRCTable: ƒ, crc32: ƒ}
isThisFormat
:
ƒ (b)
parse
:
ƒ (b)`


and if i import it like  `<script src="./papaya.js"></script>`,
it likes:
`Container
:
ƒ (p)
core
:
{Coordinate: ƒ, Point: ƒ}
surface
:
{Surface: ƒ, SurfaceGIFTI: ƒ, SurfaceMango: ƒ, SurfaceMangoData: ƒ, SurfaceVTK: ƒ}
ui
:
{Dialog: ƒ, Menu: ƒ, MenuItem: ƒ, MenuItemCheckBox: ƒ, MenuItemRadioButton: ƒ, …}
utilities
:
{ArrayUtils: {…}, MathUtils: {…}, ObjectUtils: {…}, PlatformUtils: {…}, StringUtils: {…}, …}
viewer
:
{Atlas: ƒ, ColorTable: ƒ, Display: ƒ, Preferences: ƒ, ScreenSlice: ƒ, …}
volume
:
{Header: ƒ, ImageData: ƒ, ImageDescription: ƒ, ImageDimensions: ƒ, ImageRange: ƒ, …}`,
and it works good.

I  want import it in vue project and use es6 standard like 'import'. 
how can i use papaya.js  in vue project.
thanks.

**Comment by martinezmj** [comment]
Hi.  I'm afraid I don't have experience using Vue.js.  bowser is used to find browser information and relies on `window` so not surprising it might have problems in a node environment.  If you are able to find a workaround and would like to submit a PR please let me know.  I'm always happy to add support for other environments.

**Comment by Angeluz-07** [comment]
For anyone having this issue while trying to add papaya to their vue project. I found a workaround by placing the assets in the top level directory and adding:
```
<link rel="stylesheet" type="text/css" href="assets/papaya/papaya.css" />
<script type="text/javascript" src="assets/papaya/papaya.js"></script>
```
To the index.html. By now, this allowed to me to have the viewer in my vue app.
