### ISSUE TITLE
"Error:Not a JPEG file" at Safari when  loading dicom files

### ISSUE THREAD

**Issue by harveyyeung** [rii-mango/Papaya#113]
Hi!
 Very sorry!  
 My safari version is 10.1.2, when I drop or click the file menu to select the dicom files,it has a error like "Error:Not a JPEG file".

 It all works well  at chrome and firefox.

 Best regards,
  Harvey

![20180306163511](https://user-images.githubusercontent.com/13563272/37021961-6274c7fe-215c-11e8-90bb-e96c94ff354b.png)

**Comment by rii-mango** [comment]
It's fixed now.  Thanks for reporting this.  There was a wrong build of a library causing the issue.

**Comment by harveyyeung** [comment]
thanks.best wish for you！
