### ISSUE TITLE
how to use array type of data?

### ISSUE THREAD

**Issue by JustinTQ** [rii-mango/Papaya#114]
Hello!
  I want to try to load an array of multiple raw data, but it's wrong. How should I solve it?
![image](https://user-images.githubusercontent.com/20768697/37132345-400a6a62-22c8-11e8-90ed-4b8fce19eca8.png)

![image](https://user-images.githubusercontent.com/20768697/37132256-e4d81590-22c7-11e8-80b5-40661a9abff8.png)

**Comment by martinezmj** [comment]
See this example here: https://github.com/rii-mango/Papaya/blob/master/tests/debug_server_arraybuffer.html

**Comment by ztq0924** [comment]
Thank you very much for your reply! 
But it's still wrong.

![image](https://user-images.githubusercontent.com/20768697/37187569-d3a7218a-2385-11e8-8d67-66417c3a70a2.png)
![image](https://user-images.githubusercontent.com/20768697/37187399-161a41ba-2385-11e8-876d-6fba62a9f098.png)

**Comment by ztq0924** [comment]
Thank you very much for your reply
But I do it and it's still wrong

![image](https://user-images.githubusercontent.com/20768697/37187666-3fa596e6-2386-11e8-99e0-87473cf35f26.png)
![image](https://user-images.githubusercontent.com/20768697/37187628-0989a890-2386-11e8-931e-351e1aa7c064.png)
![image](https://user-images.githubusercontent.com/20768697/37187643-1c4a4d72-2386-11e8-934e-e3e5d62b96e4.png)

**Comment by martinezmj** [comment]
`resetViewer()` might not be working for you because your JS code is running before the viewer has been created.

Try `addViewer()` like so:
```
var v = window.parent.dataArray[0];
var params = [];
params["binaryImages"] = ["v"];
papaya.Container.addViewer("mprViewer", params);
```
Try it out of the loop.  Repeatedly calling `resetViewer` in a loop probably isn't what you want to do.  `addViewer` takes a callback, so if you need to create multiple, maybe chain them using the callback, instead of all at once.

**Comment by ztq0924** [comment]
I'm sorry to reply you so long. It doesn't seem to be a good way to do it. My images are a type of 'arrayBuffer' data obtained from the server by 'WADO' , then add them to an array. Now I want to show the original data array through papaya in a viewer.
