### ISSUE TITLE
How to do 'image invert' through Papaya?

### ISSUE THREAD

**Issue by KristinWang** [rii-mango/Papaya#116]
Hi there,

I was trying to invert an image. it's not the 'flip', instead, it renders the image in grayscale in reverted way.
I am not sure how to achieve this, and I am thinking about using screenVolume.setScreenRange, or color table? 
Does anyone has suggestions about this? 
The expected result is as:
 
![image](https://user-images.githubusercontent.com/35942925/39232269-55d0f472-489f-11e8-9595-94704168267b.png)

Thanks!

**Comment by martinezmj** [comment]
You should be able to do it with something like this:

```params["luts"] = [{"name": "Inverted", "data": [[0, 1, 1, 1], [1, 0, 0, 0]] }];```

More on custom color tables: https://github.com/rii-mango/Papaya/wiki/How-To-Make-a-Color-Table

**Comment by KristinWang** [comment]
Thanks for the solution, it works great for me.

**Comment by rullator** [comment]
Hi, short follow up question.

Applying the LUT to a file would work like this
`params["file.nii"]  = {lut:"Inverted"};
`
How do I apply it directly to an encodedImage?

```
params["encodedImages"] = ["mri"];
params["luts"] = [{"name": "Inverted", "data": [[0, 1, 1, 1], [1, 0, 0, 0]] }];
??
```

**Comment by rullator** [comment]
Ahh, got it:
```
params["encodedImages"] = ["mri"];
params["luts"] = [{"name": "Inverted", "data": [[0, 1, 1, 1], [1, 0, 0, 0]] }];
params["mri"]  = {"lut": "Inverted"};
```

**Comment by niks2060** [comment]
*Thanks & Regards,*


*Nikhil D. Ghuse*

*AD – Associate Director*

Asset Management – IT (Equity)

UBS Business Solutions (India) Pvt. Ltd.

EON Free Zone 2, Kharadi,

Pune, IN.

Ph No. +918668426979
