### ISSUE TITLE
Order dicom

### ISSUE THREAD

**Issue by nhuanhoangduc** [rii-mango/Papaya#117]
Hi,

I am using papaya and can you show me which files where I can find the way dicom files are ordered?
I am going to order dicom by instance number by writing some source code, is it possible?

Thank you very much.

**Comment by martinezmj** [comment]
Look in the Daikon project: https://github.com/rii-mango/Daikon and in particular, [series.js](https://github.com/rii-mango/Daikon/blob/master/src/series.js)

See these two functions: daikon.Series.prototype.buildSeries() which calls daikon.Series.orderDicoms()
