### ISSUE TITLE
Display atlas labels in non-standard space

### ISSUE THREAD

**Issue by spiropan** [rii-mango/Papaya#118]
Hi Michael,

Is there a way (preferably without having to recompile papaya) to display atlas labels in non-standard (i.e. subject) space? I had thought that modifying the transform tag in the atlas xml file was a way to do this, but that doesn't seem to work. Any thoughts would be greatly appreciated!

Spiro

**Comment by martinezmj** [comment]
Hi.  I've added two new features that might solve this issue for you.

First, you can now set `papaya.Container.atlasWorldSpace = false`.  When false, it will use image indices for the atlas lookup.

Alternatively, you can now set `papaya.Container.atlas` with you own custom function.  See this example here: https://github.com/rii-mango/Papaya/wiki/How-To-Use-Atlases#how-to-make-a-custom-atlas

**Comment by spiropan** [comment]
Hi,

I think I understand the second custom function solution, but I'm not sure
how the first one (setting atlasWorldSpace = false) would work. Does this
solution involve the transform information, or are there additional steps
involved to be able to attach labels to any non-standard space?

Thanks

**Comment by martinezmj** [comment]
The first option doesn't involve a transform.  What it will do is pass in image indices rather than standard space, real-world coordinates to the atlas's getLabelAtCoordinate() function.  For example, maybe you don't have origin/mm information about the atlas volume, but it is in the same space as the subject volume.

That's how I interpreted the request, but let me know if that's not right.

**Comment by spiropan** [comment]
Do you mean I can specify a custom atlas in subject space using the
"atlasURL" parameter

params["atlasURL"] = "atlas/myAtlas.nii.gz";


and set atlasWorldSpace is set to false?

 papaya.Container.atlasWorldSpace = false

I don't need to worry about creating a custom build of Papaya that includes
the custom atlas?

**Comment by martinezmj** [comment]
Sorry for the late reply.   I don't see a way around the using Papaya-Builder to build the atlas into the papaya build.  But really all it's doing is converting the label XML to JSON and prepending it in the format to papaya.js.  If you want to handle creating the label data yourself, you can add something like this to your JavaScript code without needing to "recompile" papaya:

```
var papaya=papaya||{};
papaya.data=papaya.data||{};
papaya.data.Atlas=papaya.data.Atlas||{};
papaya.data.Atlas.labels = {
	atlas: {
		data: {
			label: "a:b:c:d:e"
		},
		header: {
			transform: "0.9357 0.0029 -0.0072 -1.0423 -0.0065 0.9396 -0.0726 -1.3940 0.0103 0.0752 0.8967 3.6475 0.0000 0.0000 0.0000 1.0000",
			images: {
				summaryimagefile: "Talairach_labels_1mm"
			},
			transformedname: "MNI (Nearest Grey Matter)",
			display: "*.*.*. .*",
			name: "Talairach (Nearest Grey Matter)",
			type: "Label"
		},
		version: 1
	}
};
var papayaLoadableImages = [{
	hide: true,
	name: "Talairach_labels_1mm",
	nicename: "Atlas",
	url: "data/Talairach_labels_1mm.nii.gz"
}];
```
Would it help to add an example of how to load an image directly in the custom Atlas `papaya.Container.atlas` function, so then you can do whatever you need to there in your own code.

Let me know if you have suggestions for how best to make integrating custom atlases easier.  I know this can be improved.

**Comment by spiropan** [comment]
No problem, thanks for your reply. I would like to have the labels for the
default atlas in Papaya transformed to a space other than MNI. With the
example code you just provided, could I do this by replacing the
"transform" key with a custom transform value (i.e. one from Talairach to
my space of choice other than MNI) and replacing the "data" key values with
the original from the papaya.js?

**Comment by martinezmj** [comment]
Yes, in your case, updating `transform` and `transformname` should be all you need.  Let me know if that doesn't work for you.

**Comment by spiropan** [comment]
At first pass it didn't seem to work but I'll keep at it.

On a related note, it's not immediately apparent to me how the labels are
linked to their coordinates/locations in the image (the labels in the
Talairach.xml file don't have any coordinates associated with them and the
order doesn't appear to be related to the intensity values in the
Talairach_labels_1mm.nii.gz file. Is there something I'm missing?

**Comment by martinezmj** [comment]
> order doesn't appear to be related to the intensity values 
Yes, it's the order.  In a labels/nifti pair, the image value at any XYZ coordinate is an index into the list of labels.

Try opening the atlas nifti file itself (tests/data/Talairach_labels_1mm.nii.gz) to view in Papaya, with atlas labels turned on, to get a better sense of the mapping.

**Comment by spiropan** [comment]
Ok. Still can't seem to see it. The first few labels in the Talairach.xml
file are in the cerebellum:
i.e.
<label>Right Cerebellum:Posterior Lobe:Inf Semi-Lunar Lob:Gray Matter: </
label>
but the image values in the tests/data/Talairach_labels_1mm.nii.gz in the
cerebellum are 96 or above. I seem to still be missing something?

**Comment by martinezmj** [comment]
The labels at the top of the list will have very lower indices, which means they will appear very black in the image, making them harder to see -- but they're there.  If in doubt, take the atlas image into Mango and run a 'Threshold to ROI' for the indices.  In the case of your example, indices 1 and 2.  This is where it finds them:

<img width="881" alt="screen shot 2018-07-01 at 9 26 35 am" src="https://user-images.githubusercontent.com/20823434/42135488-423b6fea-7d11-11e8-8497-f0689f47b3c8.png">

**Comment by spiropan** [comment]
Thanks for clarifying. I switched to the Harvard-Oxford Cortical Atlas
since there more fewer labels. In the Papaya viewer under the labels
section I'm only getting single letters instead of full label names. Any
idea what I'm doing wrong?


<script type="text/javascript">

        var papaya=papaya||{};
        papaya.data=papaya.data||{};
        papaya.data.Atlas=papaya.data.Atlas||{};
        papaya.data.Atlas.labels = {
        atlas: {
        data: {
        label: "Frontal Pole:Insular Cortex:Superior Frontal Gyrus:Middle
Frontal Gyrus:Inferior Frontal Gyrus, pars triangularis:Inferior Frontal
Gyrus, pars opercularis:Precentral Gyrus:Temporal Pole:Superior Temporal
Gyrus, anterior division:Superior Temporal Gyrus, posterior division:Middle
Temporal Gyrus, anterior division:Middle Temporal Gyrus, posterior
division:Middle Temporal Gyrus, temporooccipital part:Inferior Temporal
Gyrus, anterior division:Inferior Temporal Gyrus, posterior
division:Inferior Temporal Gyrus, temporooccipital part:Postcentral
Gyrus:Superior Parietal Lobule:Supramarginal Gyrus, anterior
division:Supramarginal Gyrus, posterior division:Angular Gyrus:Lateral
Occipital Cortex, superior division:Lateral Occipital Cortex, inferior
division:Intracalcarine Cortex:Frontal Medial Cortex:Juxtapositional Lobule
Cortex (formerly Supplementary Motor Cortex):Subcallosal
Cortex:Paracingulate Gyrus:Cingulate Gyrus, anterior division:Cingulate
Gyrus, posterior division:Precuneous Cortex:Cuneal Cortex:Frontal Orbital
Cortex:Parahippocampal Gyrus, anterior division:Parahippocampal Gyrus,
posterior division:Lingual Gyrus:Temporal Fusiform Cortex, anterior
division:Temporal Fusiform Cortex, posterior division:Temporal Occipital
Fusiform Cortex:Occipital Fusiform Gyrus:Frontal Operculum Cortex:Central
Opercular Cortex:Parietal Operculum Cortex:Planum Polare:Heschls Gyrus
(includes H1 and H2):Planum Temporale:Supracalcarine Cortex:Occipital Pole"
        },
        header: {
        transform: "0.8919423762  -0.1144702212  -0.1060052171
36.32398334  0.07594434596  0.9314840866  -0.2362507521  24.00593064
0.1234416279  0.255692269  0.8535607844  -24.75337909  0  0  0  1",
        images: {
        summaryimagefile: "HarvardOxford-cortl-maxprob-thr0-1mm"
        },
        transformedname: "HarvardOxford Cortical Transformed",
        display: "*.",
        name: "HarvardOxford-cortl-maxprob-thr0-1mm",
        type: "Label"
        },
        version: 1
        }
        };
        var papayaLoadableImages = [{
        hide: false,
        name: "HarvardOxford-cortl-maxprob-thr0-1mm",
        nicename: "Atlas",
        url:
"/static/papaya/build/data/HarvardOxford-cortl-maxprob-thr0-1mm.nii.gz"
        }];

        var params = [];
        params["worldSpace"] = true;
        params["images"] = ["image_transformed.nii.gz"]

       params["atlas"] = "HarvardOxford-cortl-maxprob-thr0-1mm";

 params["atlasURL"]="data/HarvardOxford-cortl-maxprob-thr0-1mm.nii.gz')
}}";;

**Comment by martinezmj** [comment]
`label` should be an array.  So it's treating the one long string like a array of characters.  Try this:
```
                    label: [
                        "Frontal Pole",
                        "Insular Cortex",
                        "Superior Frontal Gyrus",
                        "MiddleFrontal Gyrus",
                        "Inferior Frontal Gyrus, pars triangularis",
                        "Inferior FrontalGyrus, pars opercularis",
                        "Precentral Gyrus",
                        "Temporal Pole",
                        "Superior TemporalGyrus, anterior division",
                        "Superior Temporal Gyrus, posterior division",
                        "MiddleTemporal Gyrus, anterior division",
                        "Middle Temporal Gyrus, posteriordivision",
                        "Middle Temporal Gyrus, temporooccipital part",
                        "Inferior TemporalGyrus, anterior division",
                        "Inferior Temporal Gyrus, posteriordivision",
                        "Inferior Temporal Gyrus, temporooccipital part",
                        "PostcentralGyrus",
                        "Superior Parietal Lobule",
                        "Supramarginal Gyrus, anteriordivision",
                        "Supramarginal Gyrus, posterior division",
                        "Angular Gyrus",
                        "LateralOccipital Cortex, superior division",
                        "Lateral Occipital Cortex, inferiordivision",
                        "Intracalcarine Cortex",
                        "Frontal Medial Cortex",
                        "Juxtapositional LobuleCortex (formerly Supplementary Motor Cortex)",
                        "SubcallosalCortex",
                        "Paracingulate Gyrus",
                        "Cingulate Gyrus, anterior division",
                        "CingulateGyrus, posterior division",
                        "Precuneous Cortex",
                        "Cuneal Cortex",
                        "Frontal OrbitalCortex",
                        "Parahippocampal Gyrus, anterior division",
                        "Parahippocampal Gyrus,posterior division",
                        "Lingual Gyrus",
                        "Temporal Fusiform Cortex, anteriordivision",
                        "Temporal Fusiform Cortex, posterior division",
                        "Temporal OccipitalFusiform Cortex",
                        "Occipital Fusiform Gyrus",
                        "Frontal Operculum Cortex",
                        "CentralOpercular Cortex",
                        "Parietal Operculum Cortex",
                        "Planum Polare",
                        "Heschls Gyrus (includes H1 and H2)",
                        "Planum Temporale",
                        "Supracalcarine Cortex",
                        "Occipital Pole"
                    ]
```
