### ISSUE TITLE
Does 'MIP' and ' change slice thickness' possible in Papaya?

### ISSUE THREAD

**Issue by KristinWang** [rii-mango/Papaya#119]
Hi,

I want to do MIP on the image, or change the 'slice thickness' of the image, does that possible in Papaya?
I can't find related code in Papaya, so does anyone have any suggestions?
BR,
Kristin

**Comment by martinezmj** [comment]
MIP is Maximum Intensity Projection?  There isn't anything like that currently in Papaya, although it does exist in its sister application Mango (closed source though).  You would most likely need to add that yourself, but I'd be happy to point you in the right direction if you wanted -- and also would be interested in a PR if you were to do it.

Changing slice thickness.  I'm assuming you mean to re-slice the data, not just change the metadata.  Similar to MIP, it exists in Mango, but not Papaya.  It should be possible to do this interpolation in Papaya.  Again, I can point you in the right direction if that's what you want.

**Comment by KristinWang** [comment]
Thanks for the reply.  You got me right on this and I sent you an email  through github mail with more details. Again, really appreciate your help.

**Comment by martinezmj** [comment]
Unfortunately there isn't any code I can point you to as an example of MIP and changing the slice thickness.  If you are wanting to tackle these features, please feel free to ask questions and I'll be happy to help along.  I'm not sure where to start though -- you'll just need to jump in!

**Comment by KristinWang** [comment]
Thanks for you advice on this, we will do some investigation and see how to do with it.
I really appreciate your work, thanks again!
