### ISSUE TITLE
Error while loading a dicom folder

### ISSUE THREAD

**Issue by KristinWang** [rii-mango/Papaya#120]
Hi there,

I was trying to load a local dicom folder, but the papaya viewer throw an error saying ""Offset is outside the bounds of DataView".
What is the possible reason for that? I can correctly load a dicom file/folder, if it is the file papaya demo used, but I can't make it work when use my own local dicom file/folder.

The dicom folder is a series from some hostpital, seems normal...
So I really don't know what's wrong.
![image](https://user-images.githubusercontent.com/35942925/40298373-8839947a-5d15-11e8-8adc-80178e7333df.png)

Thanks,
Kristin

**Comment by martinezmj** [comment]
Is it possible to send the series or an anonymized version of it?  Seeing the stacktrace from the console may also help.  It sounds like you're using the feature correctly.  Wild guess: maybe there's some images that don't contain image data, like modality SR?  I'm not sure how Papaya would handle that.  Maybe you can try a few images at a time to pinpoint which ones are causing the issue

**Comment by KristinWang** [comment]
Thanks for the reply. I have sent you the sample images to you github mail and hope to here from you again. It's really appreciated!

**Comment by martinezmj** [comment]
I believe this is the same issue as this: https://github.com/rii-mango/Daikon/issues/17 and has been fixed.
