### ISSUE TITLE
Problem in loading same DICOM images

### ISSUE THREAD

**Issue by Ashokcharu** [rii-mango/Papaya#121]
I have an array that contains list DICOM slices. 

```
    var data = [["image.740","image.740","image.741","image.742","image.742"]];
    params["images"] = data;
```
I have 5 slices in my array. When I click `+` `-` buttons I can see only three slices in the viewer. Remaining two slices not visible. Sometimes the last slice coming first.

For an example, The 10 images having the same file name. First, the count `z` show 10. And When I click `+` `-` buttons, It should move one by one all 10 images.

Thanx

**Comment by martinezmj** [comment]
Hi.  You [posted this also on StackOverflow](https://stackoverflow.com/questions/50507286/papaya-dicom-viewer-moving-slice-not-working-when-its-same), was your questions answered there?

It's a little confusing.  Your data array contains three unique slices (and two duplicates) so it makes sense that you only see three images.  Also note that the slices are ordered according to their metadata (see Slice Position) -- the order that you put them in the array doesn't matter.

**Comment by Ashokcharu** [comment]
@martinezmj  Thanks for your suggestion and sorry for my late reply. Now my problem resolved. Thanks again.
