### ISSUE TITLE
Ruler should be drawn on current slice

### ISSUE THREAD

**Issue by niks2060** [rii-mango/Papaya#123]
I am working on papaya viewer and Implemented a dynamic ruler but issue is that when i draw a ruler it get applied to all slices of that view.

**Comment by martinezmj** [comment]
Yes, the built-in ruler is static and applies to all slices.  Perhaps you can listen in `papaya.Container.prototype.coordinateChanged` and update your ruler there based on slice.  You'd need to maintain your own data structure for the ruler points.

**Comment by niks2060** [comment]
I have found the solution for that by maintaining my own data structure
