### ISSUE TITLE
How to remove ordering the slices according to metadata

### ISSUE THREAD

**Issue by Ashokcharu** [rii-mango/Papaya#124]
I want to ignore ordering the slices according to metadata. 

For an example, My array format like this below

`params['images'] = [['1.dcm','2.dcm','3.dcm']];`

How I given my array order, same like that, I want to see the slices order in my viewer.

Thanks

**Comment by martinezmj** [comment]
There are two new options that should solve this for you: 
```
daikon.Series.useExplicitOrdering= true;  // ignore metadata-based ordering
daikon.Series.useExplicitSpacing=2; // set what spacing you'd like to use in mm
```

More info here: https://stackoverflow.com/questions/51042560/how-to-remove-ordering-the-slices-according-to-metadata

**Comment by Ashokcharu** [comment]
Yeah, now it's working perfectly... Thanks
