### ISSUE TITLE
how to translate from brightness/contrast  to dicom windowWidth/windowCenter

### ISSUE THREAD

**Issue by hu3402379** [rii-mango/Papaya#126]
Hi, @martinezmj 
sorry for my trouble.
Now, i have a question, when i use mouse right-click and drag to adjust brightness/contrast, i want to show current value on left bottom of image.  the brightness/contrast value is not dicom tag  default windowWidth/windowCenter, i need to translate them to windowWidth/windowCenter. 
I don't know how to translate them.
can you help me or give me some suggestion?
Thanks very much.

![image](https://user-images.githubusercontent.com/7867792/42033225-bdf9ae12-7b0e-11e8-88b4-6cfaa86b8c61.png)

**Comment by martinezmj** [comment]
See the function `papaya.viewer.Viewer.prototype.windowLevelChanged` in viewer.js.  Note that Papaya stores this data in a min/max form.  To convert it to center/width form:
width = max-min
center = min + (width / 2)

**Comment by hu3402379** [comment]
@martinezmj Thanks for your reply.  That looks very good!! 
and i have another question, i want to set default ww/wc, something like width=500, center = -300.  or width=1500, center= -600. 

And i will call 
>papaya.viewer.Viewer.prototype.windowLevelChanged = function (contrastChange, brightnessChange) 

function.
how can i translate width/center  to contrastChange/brightnessChange? so i can pass params  to windowLevelChanged ()?

thanks again!
