### ISSUE TITLE
Removing the two right viewers from the orthogonal viewer

### ISSUE THREAD

**Issue by GabrielBisson** [rii-mango/Papaya#127]
Hello,
To be more precise, I am only interested in displaying the axial plane. Thus, my objective is to remove the sagittal and coronal viewer. 

The only way I found to do that was to add padding on the right side. Is there a way to completely remove them and adjust the overall viewer in consequence?

Thank you
Gabriel

**Comment by martinezmj** [comment]
Yes, see the `orthogonal` and `mainView` options: https://github.com/rii-mango/Papaya/wiki/Configuration#ui-parameters

```
params["orthogonal"] = false;
params["mainView"] = "axial";
```

**Comment by GabrielBisson** [comment]
![sideviewers](https://user-images.githubusercontent.com/35878767/42110279-8327bdb0-7bae-11e8-9db3-9cac34e22b65.png)

Thanks for the quick reply. 

However I already  tried this solution. As you can see in the image attached, even if the views are not displayed, the placeholders remain. So let me reformulate: How can I crop it as to show only the mainView (in this case the axial view)?

**Comment by martinezmj** [comment]
Can you post all the parameters that you're using to configure Papaya?  That's not what it's suppose to look like.  When orthogonal=false, the two smaller views will not show.  For example:

![screen shot 2018-06-29 at 3 05 26 pm](https://user-images.githubusercontent.com/20823434/42112559-e1982462-7bad-11e8-87e7-4be04b80a4f7.png)

**Comment by GabrielBisson** [comment]
Here they are :

`var params = []
params["images"] = ['Abdomen C+.nii']; 
params["showControls"] = false;
params["expandable"] = true;
params["orthogonal"] = false;
params["mainView"] = "axial";`

**Comment by GabrielBisson** [comment]
I am not using any API calls. I have no errors in the console either. The only thing I have is a warning related to the browser (I am using Firefox version 60.0.1 (64-bit)).
Here's the warning:
`Use of mozImageSmoothingEnabled is deprecated. Please use the unprefixed imageSmoothingEnabled property instead.  papaya.js:3401:124`

**Comment by GabrielBisson** [comment]
With the latest commit everything works fine. 
Thanks for the help
