### ISSUE TITLE
Right side views not visible

### ISSUE THREAD

**Issue by algates90** [rii-mango/Papaya#129]
Hi,

I am new to use papaya js. It would be great if someone could help on this. @martinezmj 

Problem : Right side views are not visible.

HTML : `<div class="papaya" data-params="params"></div>`
The below params are used at the time of load.
params["kioskMode"] = true;
params["orthogonal"] = true;
params['combineParametric'] = true;

Dynamically an array of js file objects belonging to same series are passed to params["files"].
params["files"] = selectedSeriesFiles;

Once the files are set, I call the API function 
papaya.Container.resetViewer(0, params);

This loads the corresponding files into the view, but not the right side views.

Note . This works correctly when the same set of files are loaded using File -> Add Image

Sample images 
![image](https://user-images.githubusercontent.com/30894700/42585566-43ab9aa8-8536-11e8-89d1-e8c651e94701.png)

When loaded using File->Add Image

![image](https://user-images.githubusercontent.com/30894700/42585719-b42d627a-8536-11e8-8fd5-24f6ca964f7a.png)

**Comment by martinezmj** [comment]
Hi.  I wasn't able to recreate this unfortunately.  It looks like you're doing everything correctly.  I created a file tests/debug_server_files.html that recreates this scenario.  Maybe you can test it.  The images I was testing with are tests/data/sample_image.nii.gz and zstat1.nii.gz.

Also, check the JavaScript console.  Are there any errors?
