### ISSUE TITLE
 Changing keyboard shortcuts

### ISSUE THREAD

**Issue by AndreDiler** [rii-mango/Papaya#130]
Hello,

To be more precise, I am looking for a way to change the default from (Alt)(Left-click and drag to zoom) to (Right-click and drag). Similarly, I want to change the brightness/contrast from (Right-click and drag) to (Crtl-Left-click and drag)

Thank you,

Andre

**Comment by martinezmj** [comment]
Are you looking for where in the code to change this or a new feature, like a setting, to manage this? 

In the code, the place where this is handled is `papaya.viewer.Viewer.prototype.mouseDownEvent`.  Specifically, look for the lines of code where it sets:  `this.isWindowControl = true;` and `this.isZoomMode = true;`  Note the use of `isControlKeyDown` and `isAltKeyDown`.

**Comment by AndreDiler** [comment]
It worked perfectly 

Thank you
