### ISSUE TITLE
Cropped Volume in Canvas

### ISSUE THREAD

**Issue by AndreDiler** [rii-mango/Papaya#132]
Hello,

As seen on the attached pictures, we have 3 issues.

![padding](https://user-images.githubusercontent.com/30091846/42710297-6fc92c14-86b1-11e8-8d66-dd3a9a7c2166.png)

![padding2](https://user-images.githubusercontent.com/30091846/42710296-6faec3b0-86b1-11e8-9a53-06fc9c5c3c8e.png)

1- It appears that the volumes are cropped (we can see it on the volume on the right)
2- The volumes don't take all the space of the canvas
3- The volumes don't appear to be the same size even though they are both 512x512 : `Image Dimensions (1-8): 3, 512, 512, 167, 1, 1, 1, 1` on the left and `Image Dimensions (1-8): 3, 512, 512, 199, 1, 1, 1, 1` on the right

Is it possible to solve these ?
Thank you,

Andre

**Comment by martinezmj** [comment]
Need more info.  This could be many things: image-related, configuration-related, etc.  In general, yes you are right that a square image should fill the viewer space.

Is it possible to share the images with me?  Also, what parameters are you using to configure Papaya?

**Comment by AndreDiler** [comment]
I figured it was caused by image itself.

Thanks
