### ISSUE TITLE
Is there any possibility to view jpeg images in papaya Dicom viewer?

### ISSUE THREAD

**Issue by Ashokcharu** [rii-mango/Papaya#133]
I want to view the JPEG images in papaya Dicom viewer (`Only main view`).

Because I need xy position and xy coordinates have same like DCM images.

Is it possible in papaya Dicom viewer?

**Comment by martinezmj** [comment]
This is probably possible with some minor effort.  The compression used in DICOM is JPEG, so the decoders are already there.  There aren't any plans to make this a feature in Papaya, but if you wanted to tackle this yourself, I can point you in the right direction.

**Comment by martinezmj** [comment]
Alternatively, there are command-line tools out there that can convert between jpeg and DICOM.  Take a look at dcmtk: https://support.dcmtk.org/docs/img2dcm.html

**Comment by Ashokcharu** [comment]
@martinezmj Thanks for your reply, I will try with your example.
