### ISSUE TITLE
Could the volume rendering of  nii files be supported?

### ISSUE THREAD

**Issue by hainawa** [rii-mango/Papaya#134]
I looked up in the docs, and found only GIFTI and Mango surface datas are supported

**Comment by martinezmj** [comment]
Do you mean generating surface data directly, in Papaya, from NIFTI image data?

**Comment by hainawa** [comment]
yes,I want to know if its possible

**Comment by martinezmj** [comment]
Papaya reads surface data files like GIFTI or VTK, but it doesn't yet support the feature of generating surface data (i.e., triangles) from image data like NIFTI.  You'd have to use another application like Mango or Freesurfer to generate the surface data.

**Comment by hainawa** [comment]
Thank you very much.If I want to transfer NIFTI to GIFTI on server side, could Mango or Freesurfer help?

**Comment by martinezmj** [comment]
Mango -- there is command-line scripting support.  See the example usage in [this thread](http://rii.uthscsa.edu/mango/forum/viewtopic.php?f=3&t=1527&sid=9bb1c2a251c2caa7a5bc534bba2d60f0) and more [on scripting](http://rii.uthscsa.edu/mango/scripttutorial.html).

Freesurfer -- More geared for command-line usage: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferCommands

**Comment by MarlonLiu1991** [comment]
> Mango -- there is command-line scripting support. See the example usage in [this thread](http://rii.uthscsa.edu/mango/forum/viewtopic.php?f=3&t=1527&sid=9bb1c2a251c2caa7a5bc534bba2d60f0) and more [on scripting](http://rii.uthscsa.edu/mango/scripttutorial.html).
> 
> Freesurfer -- More geared for command-line usage: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferCommands

Is there other open source for transfering NIFTI to surface data? Thans in advance
