### ISSUE TITLE
Using `encodedImages` without putting variables in `window`

### ISSUE THREAD

**Issue by chrisfilo** [rii-mango/Papaya#136]
We are working on building a [jupyterlab extension for viewing nifti files](https://github.com/akeshavan/nii_extension). The extension framework passes base64 encoded data which we can load in Papaya, but unfortunately it does not allow us to put variables as `window` fields. To work around it we had to declare a standalone global variable to store the base64 data. However, papaya expects all variables to be in ` window` to work around this we had to override internal Papaya function:
```
papaya.utilities.ObjectUtils.dereference = function (name: string) {
      return name;
};
```

Can you think of a neat modification of Papaya that could enable our use case without breaking backwards compatibility?

**Comment by rii-mango** [comment]
I've added a fix such that now you can just pass the variable itself (instead of variable name).  For example:

```
var myEncodedImage = "..."
var params = [];
params["encodedImages"] = [myEncodedImage]; 
```

Does this fix it for you?
