### ISSUE TITLE
Change the alpha (transparency) of the image using a keypress

### ISSUE THREAD

**Issue by AndreDiler** [rii-mango/Papaya#137]
Hello, 

I am looking for a way to dynamically change the alpha with a key press.
To be more specific, I wish to set  the transparency to it's maximum value when a key is pressed  and set it to it's minimum when another key is pressed.

I can't seem to find a clear way to modify it in the current implementation of the transparency changer in the source code. 

Thanks for your help

**Comment by martinezmj** [comment]
You can do it like this:
```
papayaContainers[0].viewer.screenVolumes[1].alpha = 0.5;  // 0 to 1
papayaContainers[0].viewer.drawViewer(true, false);
```
screenVolumes[1] would mean the first overlay (or second image in the stack).

**Comment by AndreDiler** [comment]
Everything worked great!
Thanks a lot
