### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by chrisgorgo** [rii-mango/Papaya#138]
It would be beneficial for some advanced use cases for papaya to be published on npm.

**Comment by vsoch** [comment]
+1! I was just coming here to post this! What would it take to make it a modular package? I think @akeshavan is interested in this too :)

**Comment by MarlonLiu1991** [comment]
You use it for desktop app?

**Comment by vsoch** [comment]
Likely they mean a package you can install with npm to use within server side JavaScript (nodejs) so it will render in a web interface. But in this context if you used electron it likely could be considered a desktop application.

**Comment by MarlonLiu1991** [comment]
If you use electron to build the application, you should add parameters in main.js as follow: webPreferences: { nodeIntegration: false }

**Comment by martinezmj** [comment]
Now on npm: https://www.npmjs.com/package/papaya-viewer
