### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by vinhton123** [rii-mango/Papaya#139]
Hello,

I have copy and pasted the basic usage snippet of code onto a new .html, but when I open the document on a browser, I receive these errors:

papaya.js:3481 Uncaught ReferenceError: $ is not defined
    at Function.papaya.Container.buildAllContainers (papaya.js:3481)
    at papaya.Container.startPapaya (papaya.js:3482)

Would you be able to assist me with this please?

**Comment by rii-mango** [comment]
Looks like it can't find JQuery.  Maybe you are using a build that doesn't include it and aren't including it yourself?

Try this build here, which does include JQuery: https://github.com/rii-mango/Papaya/tree/master/release/current/standard

**Comment by vinhton123** [comment]
I tried your suggestion, and the blank viewer works now! Thank you so much.

However, I am still having trouble preloading images. I receive this error when I use the preload code snippet.

<img width="1050" alt="screen shot 2018-08-12 at 7 27 37 pm" src="https://user-images.githubusercontent.com/23654164/44010258-2d29b492-9e66-11e8-8bda-b9cb7e3bdbf6.png">

**Comment by rii-mango** [comment]
Are you running it on a server?  You need to run it on a server if you are specifying URLs for the images.

**Comment by vinhton123** [comment]
Gotcha; I am running it on a server now, and it is working as intended. Thanks so much for your ongoing support.
