### ISSUE TITLE
Semi kiosk mode

### ISSUE THREAD

**Issue by hanke** [rii-mango/Papaya#14]
It would be nice to have a mode where the menus for adding images and global preferences are disabled (as in kiosk mode), but the user can still alter the parameters of the LUTs.

Thanks!

**Comment by rii-mango** [comment]
This has been added.  Set both 'kioskMode' and 'showControlBar' to true.

![screen shot 2015-07-09 at 9 47 31 am](https://cloud.githubusercontent.com/assets/1859709/8598300/90a7f758-261f-11e5-8add-17699bf37118.png)
