### ISSUE TITLE
how to do mpr mip

### ISSUE THREAD

**Issue by yiuyiu** [rii-mango/Papaya#142]
hello ~
i used to use papaya but i thought it cost long time to load all series. so in my new app, i use the cornerstone, because it can load series one by one. But now i have to implement mpr and mip in my web app, i need to do mpr and mip by myself. 
But papaya source is too difficult for me, and i have not access medical areas  so i have no direction to do this. o(╥﹏╥)o .
Could you give some advice or articles to do this, the only refer i know is Dicom standard.  thank you

**Comment by rii-mango** [comment]
Papay already has basic support for MPR, see the Rotation controls here: https://github.com/rii-mango/Papaya/wiki/User-Interface-Features

MIP would be much more work.  I can provide direction in how to access the image data through Papaya.  Let me know if you are still interested in this.
