### ISSUE TITLE
how to cite

### ISSUE THREAD

**Issue by CPernet** [rii-mango/Papaya#146]
I'd like to reference Papaya in a paper, how do we cite the software, I could not find an article I could use

**Comment by martinezmj** [comment]
The closest we have are the publications listed on this page here: http://rii.uthscsa.edu/mango/

This is from the Mango parent project.  You might reference Papaya as the "web version of Mango" and can also cite this Github project page.

**Comment by CPernet** [comment]
ok thx - now referenced
