### ISSUE TITLE
Flipped images are show 

### ISSUE THREAD

**Issue by niks2060** [rii-mango/Papaya#150]
![flip image](https://user-images.githubusercontent.com/11830418/50216598-38941d80-03ac-11e9-8cfd-401239571878.png)

Expected Result

![original](https://user-images.githubusercontent.com/11830418/50216705-87da4e00-03ac-11e9-9556-c4127c017eaf.png)

**Comment by NicolasRannou** [comment]
you should probably share the anonymized DCM image you are trying to visualize if possible in order to get some help...

**Comment by niks2060** [comment]
@NicolasRannou  Please find the attached anonymized DCM image



[1.2.276.0.7230010.3.1.4.186695702.7036.1545305962.383.zip](https://github.com/rii-mango/Papaya/files/2698755/1.2.276.0.7230010.3.1.4.186695702.7036.1545305962.383.zip)

**Comment by niks2060** [comment]
i was my issue just set the  params["radiological"] = true; 
if changed to params["radiological"] = false; it is working as expected

**Comment by niks2060** [comment]
i was my issue just set the  params["radiological"] = true; 
if changed to params["radiological"] = false; it is working as expected
