### ISSUE TITLE
How to add new screen slice to the viewer

### ISSUE THREAD

**Issue by nikgetas** [rii-mango/Papaya#152]
Hi,

Thank you for this fantastic project! I'm quite new to js programming and want to add a customized volume to the main viewer but don't have a clue. Right now, I have set the `orthogonalTall` to true globally and want to add a big slice to show something else at the right side, see the picture. Could you please show me which functions I should look to and how to do that? Thank you in advance!

Best,

![capture](https://user-images.githubusercontent.com/12049744/51624438-d11c4100-1f08-11e9-9e9a-3618ff4166a2.PNG)

**Comment by MarlonLiu1991** [comment]
Hi nikgetas, have you solved this problem? I have a question likes yours

**Comment by nikgetas** [comment]
@MarlonLiu1991 Basically, I've done this layout by re-allocating the surface viewer to the right. I think it's not the best way but simply works.

**Comment by MarlonLiu1991** [comment]
@nikgetas Have you modified the source code?  Or just change ralated parameters be similar to follows: "params["encodedImages"] = ["myImage"]; " ?

**Comment by nikgetas** [comment]
Yes, I've changed source js code

**Comment by MarlonLiu1991** [comment]
@nikgetas  Can you tell me where the location of ralated source js code? Thanks a lot!

**Comment by nikgetas** [comment]
@MarlonLiu1991 Sure. The src code of viewer's layout is all located at `viewer.js` and you may want to look at the functions: 
`papaya.viewer.Viewer.prototype.drawScreenSlice` `papaya.viewer.Viewer.prototype.calculateScreenSliceTransforms`

**Comment by MarlonLiu1991** [comment]
Thanks for your help@nikgetas
