### ISSUE TITLE
How to get Current slice image pixel data and byte Array to calculate standerd mean deviation for ROI (Rectangle / Ellipese) and HU

### ISSUE THREAD

**Issue by niks2060** [rii-mango/Papaya#153]
I am trying to draw annotations like ROI(Rectangle and Ellipse) and HU(Pixel probe) I need to calculate current slice or image byteArray and pixel data and I am not able to find it.
I have tried
1)  'new Uint8Array(this.mainImage.imageData[this.mainImage.currentSlice])' and 
2) 'this.mainImage.screenVolumes[0].volume.imageData.data.buffer)' but no luck as it deffers 
the image that i have posted is using 2nd option but it is not correct as i need to find pixeldate of current image. in mainImage screenslice.
thanks in advance please help me out to find it...
regards Nikhil

![untitled](https://user-images.githubusercontent.com/11830418/51656287-78ab7900-1fc6-11e9-86f9-9d5317625519.png)

**Comment by niks2060** [comment]
hi martin,
Thanks for your reply,
I don't want this `papayaContainers[0].viewer.screenVolumes.getVoxelAtIndex(x, y, slice, timepoint, true).` I want pixel data of each screen slice that you are adding while creating volume 
'this.screenVolumes[0].volume' have pixel data created from each screen slice.

I want each Image pixel data which is shown as follows,
![dicomparser](https://user-images.githubusercontent.com/11830418/52195424-e3d63480-287d-11e9-89f7-e535619e1394.png)

**Comment by martinezmj** [comment]
Look into `axialSlice`, `coronalSlice` and `sagittalSlice` in Viewer.  They can also be referenced as `mainImage`,`lowerImageTop` and `lowerImageBot`.  These are all instances of ScreenSlice.  In a ScreenSlice, look for` imageData`.  It's a 2-D array, as in: `imageData[screenVolumeIndex][voxelIndex]`.  You would need to calculate the voxel index based on the dimension in that slice direction.  This array stores the values of `getVoxelAtMm` for the slice that's currently being displayed.  It would be appropriate to use this data for calculating stats.

**Comment by martinezmj** [comment]
Hi.  I guess you want the raw pixel data?  Try this:

```
papayaContainers[0].viewer.screenVolumes[0].volume.imageData.data
```

Of course, the raw data hasn't had anything like data scales applied to it, so it's much harder to work with than `getVoxelAtIndex`.  `getVoxelAtIndex` abstracts away all the work of interpreting the raw data for you.

**Comment by martinezmj** [comment]
And that's the raw pixel data for the entire series.  Knowing how to index into all that raw data to find the data for a specific slice (say the current slice in the viewer) is exactly what `getVoxelAtIndex` does.
