### ISSUE TITLE
Zoom must be centralised 

### ISSUE THREAD

**Issue by niks2060** [rii-mango/Papaya#154]
Zoom must be centailsed

**Comment by martinezmj** [comment]
Are you saying that the point where it zooms should be the center of the image?  Currently, it zooms at the location of the crosshairs.  It wouldn't be hard to add an option to always zoom at the center, if that's what you mean.

**Comment by niks2060** [comment]
Hello Martin that's what i want.
Cant you just tell me where should I change  so that zoom will be centralised

**Comment by niks2060** [comment]
i got It thanks ..
