### ISSUE TITLE
displayMin error

### ISSUE THREAD

**Issue by dverkhovsky13** [rii-mango/Papaya#155]
After I use method papaya.Container.resetViewer(0, params); in my application I'll get an error that says: "Uncaught TypeError: Cannot read property 'displayMin' of null". Does anybody know a solution?
![image](https://user-images.githubusercontent.com/39799954/53016553-eda38e80-345e-11e9-8e79-ce05671f2b2a.png)

**Comment by martinezmj** [comment]
Hi.  I haven't been able to recreate this.  Are you using NIFTI or DICOM images?  Can you share your params?

**Comment by dverkhovsky13** [comment]
These are  my params: 
![image](https://user-images.githubusercontent.com/39799954/54129211-cff29500-441e-11e9-9104-f0e7e0326277.png)
