### ISSUE TITLE
is the allowScroll configuration setting effective?

### ISSUE THREAD

**Issue by rprimet** [rii-mango/Papaya#157]
From a cursory reading (and a few tests of Papaya on small screens) `window.scrollTo` seems to be regularly called (e.g. on size changes) regardless of whether `allowScroll` is set. What is the effect of the `allowScroll` setting?

**Comment by martinezmj** [comment]
That setting refers to being able to change the current slice with the scroll wheel.  I've updated the documentation to be a little clearer: https://github.com/rii-mango/Papaya/wiki/Configuration#ui-parameters

**Comment by rprimet** [comment]
Thanks! Closing this issue then.
