### ISSUE TITLE
How to reset Window level to default value

### ISSUE THREAD

**Issue by niks2060** [rii-mango/Papaya#158]
I want to reset whatever changed values after applying window level to its default value

**Comment by rii-mango** [comment]
You can now call, `resetScreenRange()`.  For example:
```
papayaContainers[0].viewer.screenVolumes[0].resetScreenRange();
papayaContainers[0].viewer.drawViewer(true);
```

**Comment by niks2060** [comment]
Thanks.. It's working as expected
