### ISSUE TITLE
How to reset zoom and pan to initial values

### ISSUE THREAD

**Issue by niks2060** [rii-mango/Papaya#160]
I have tried to reset Zoom and pan of the current viewer by using following piece of code
  this.axialSlice.updateZoomTransform(1, 1, 1, 0, 0, 0);
  this.coronalSlice.updateZoomTransform(1, 1, 1, 0, 0, 0);
  this.sagittalSlice.updateZoomTransform(1, 1, 1, 0, 0, 0);
  this.axialSlice.zoomFactor = 1;
  this.coronalSlice.zoomFactor = 1;
  this.sagittalSlice.zoomFactor = 1;

but it holds the zoomFactor so that when I am trying to zoom it again it starts zooming from last position again after reset.

**Comment by martinezmj** [comment]
```
papayaContainers[0].viewer.zoomFactorPrevious = 1;
papayaContainers[0].viewer.setZoomFactor(1);
papayaContainers[0].viewer.drawViewer(true);
```

The state of the application is mostly held in the viewer, not the "slices".

**Comment by niks2060** [comment]
It solved my issue..
