### ISSUE TITLE
The two slices are restricted to move up and down i.e Coronal and Sagittal.

### ISSUE THREAD

**Issue by niks2060** [rii-mango/Papaya#161]
![img_20190314](https://user-images.githubusercontent.com/11830418/54354596-104f4e80-467d-11e9-9153-c753121585d9.png)

When I am trying to zoom image and PAN it it only pan to left right as pan to top and bottom is restricted for  Coronal and Sagittal screenslices

**Comment by martinezmj** [comment]
When the main view is axial, then you are panning in either the left-right or anterior-posterior directions.  For two others views, sagittal and coronal, the top-bottom direction is superior-inferior.  Since you're not panning the axial slice in a superior-inferior direction, you shouldn't expect the coronal and sagittal views to move up down, only left and right.

**Comment by niks2060** [comment]
Hi martinez,
I am taking about  sagittal and coronal is in main View still this happened

**Comment by martinezmj** [comment]
Hi, I'm sorry, but I'm not understanding the problem.  Can you explain it again?  Some more screenshots may help.  Thanks.

**Comment by niks2060** [comment]
Let Me explain 
1) AXIAL IN MAIN IMAGE
![img_20190325_01](https://user-images.githubusercontent.com/11830418/54915492-457d5b80-4f1d-11e9-8945-4164b92ba6b2.png)

2) CORONAL IN MAIN IMAGE
![img_20190325_02_C](https://user-images.githubusercontent.com/11830418/54915512-51691d80-4f1d-11e9-9588-1ea705f8ed1a.png)

3) SAGITTAL IN MAIN IMAGE
![img_20190325_03_S](https://user-images.githubusercontent.com/11830418/54915544-63e35700-4f1d-11e9-9de9-63dad7b14c68.png)

**Comment by martinezmj** [comment]
Hi.  I've never been able to recreate this one.  Do you notice it only in certain browsers or only for certain images?  I am able to pan in all direction for all slices.  Something is missing.

**Comment by niks2060** [comment]
If that so I need to find exactly what is
