### ISSUE TITLE
Not able to find current Screen slice in Coronal and Sagittal View

### ISSUE THREAD

**Issue by niks2060** [rii-mango/Papaya#162]
on Click need to find slice contained in mainImage but not able to do it as image canvas start from some (x,y) from top.
It is always null. I need it for stack calculations 
**

> this.selectedSlice.screenDim / Math.max(this.selectedSlice.sliceCounts, 8)

**

![img_20190319](https://user-images.githubusercontent.com/11830418/54588677-a8688180-4a49-11e9-9b45-9d0f82187c9f.png)

**Comment by martinezmj** [comment]
Look at the `currentCoord` property of the viewer.  It's the XYZ of the current slices.  Does that work for you?

**Comment by niks2060** [comment]
hello martinez,
It is not working
 if (this.insideScreenSlice(viewer.axialSlice, xLoc, yLoc, viewer.volume.getXDim(), viewer.volume.getYDim())) {
        this.selectedSlice = this.axialSlice;
    } else if (this.insideScreenSlice(viewer.coronalSlice, xLoc, yLoc, viewer.volume.getXDim(),
            viewer.volume.getZDim())) {
        this.selectedSlice = this.coronalSlice;
    } else if (this.insideScreenSlice(viewer.sagittalSlice, xLoc, yLoc, viewer.volume.getYDim(),
            viewer.volume.getZDim())) {
        this.selectedSlice = this.sagittalSlice;
    } else if (this.insideScreenSlice(viewer.surfaceView, xLoc, yLoc, viewer.volume.getYDim(),
            viewer.volume.getZDim())) {
        this.selectedSlice = this.surfaceView;
    } else {
        this.selectedSlice = null;
    }

In above code it won't satisfy any condition and return '  this.selectedSlice = null;'

**Comment by niks2060** [comment]
I got it thanks martinez.
