### ISSUE TITLE
how to build 

### ISSUE THREAD

**Issue by hongliang666** [rii-mango/Papaya#167]
I want to change the background of toolbar, after changing the code, how to build the papaya? May I build it in Windows PowerShell?

**Comment by martinezmj** [comment]
Have you seen this: https://github.com/rii-mango/Papaya/wiki/How-To-Build-Papaya

**Comment by MarlonLiu1991** [comment]
> Have you seen this: https://github.com/rii-mango/Papaya/wiki/How-To-Build-Papaya
Thanks for your reply, it has been solved.
