### ISSUE TITLE
How to get the file which is selected?

### ISSUE THREAD

**Issue by MarlonLiu1991** [rii-mango/Papaya#170]
After I click the "File" and then click the "Add Image", I choose a data file such as nifti file, and I want to process the data file in other ways, where can I get the data file after It is loaded in papaya?Please give some advice, thanks in advance!

**Comment by martinezmj** [comment]
I'm guessing that you want to manipulate the image data after it has been loaded into Papaya?  Try this:

```
var volume = papayaContainers[0].viewer.screenVolumes[0].volume;
var imageData = volume.imageData.data;

// if image dims are useful
var xDim = volume.getXDim();
var yDim = volume.getYDim();
var zDim = volume.getZDim();

for (var ctr = 0; ctr < imageData.byteLength; ctr += 1) {
    if (imageData[ctr] > 128) {  // do something here
        imageData[ctr] = 0;
    }
}

papayaContainers[0].viewer.drawViewer(true);
```

**Comment by MarlonLiu1991** [comment]
The image dims is also very useful, thanks
