### ISSUE TITLE
Can't get canvas of papaya

### ISSUE THREAD

**Issue by hongliang666** [rii-mango/Papaya#173]
I want to draw some curves on papaya, I have tried as below:
        var canvas = papaya.viewer.Viewer.canvas;
        var context = papaya.viewer.Viewer.canvas.getContext("2d");
but an An error occurred： Uncaught TypeError: Cannot read property 'getContext' of undefined。
How can I solve this problem? Thanks a lot

**Comment by Mmasoud1** [comment]
If you have one viewer, then you can try this:
 papayaContainers[0].viewer.canvas.getContext("2d")
