### ISSUE TITLE
Go to coordinate

### ISSUE THREAD

**Issue by mikaelkahkonen** [rii-mango/Papaya#175]
Hi,

Thanks a lot for the great tool! I'm trying send the user dynamically to a coordinate (for example [10,-18,6]). How would I do that with js?

EDIT: Figured this out, I'll write the solution here if it's okay and someone else has this problem too. `papayaContainers[0].viewer.gotoCoordinate(coord);`, and `coord` should be an object with 'x', 'y' and 'z' properties. Origin for these coordinates is different from the origin of the coordinates in the viewer, so you'll have to do a simple conversion if you want to use those.

Thanks
Mikael

**Comment by martinezmj** [comment]
That's it.  There's also a `coordinate` parameter you can use.

```
params["coordinate"] = [0, 0, 0];
```
