### ISSUE TITLE
Cursor coordinates become invalid on screen orientation change.

### ISSUE THREAD

**Issue by hanke** [rii-mango/Papaya#18]
I haven't tracked this down, but wanted to report it:

Papaya doesn't handle screen orientation changes completely. When I rotate the screen by 90 degrees the canvas coordinates no longer match the canvas content -- there maybe even an axis flip. When rotated back everything is fine again.

Sorry for the vague description.

**Comment by rii-mango** [comment]
Sorry for taking so long to reply to this.  I think the issue probably got fixed somewhere along the way since you reported it.  I cannot recreate it any longer.  Let me know if you still see the issue.
