### ISSUE TITLE
When starting papaya as module, image isn't loaded

### ISSUE THREAD

**Issue by stjjelic** [rii-mango/Papaya#197]
When starting Papaya as js module the image won't load into the viewer.

`function initializePapaya(param) {
    var image = param;
    $(document).ready(function () {
        var params = [];
        params["images"] = [image];
        papaya.Container.startPapaya(params);
    });
}`

When debugging, there is my image in "params" at papaya.Container.startPapaya(params);. But no image is loaded into the viewer.

![imageppy](https://user-images.githubusercontent.com/45634927/107986139-bcb5b000-6fcb-11eb-9d32-b15dffa6bd65.png)

**Comment by cynde** [comment]
Hi! How do you solve this?
