### ISSUE TITLE
Client loading received image

### ISSUE THREAD

**Issue by cosminbvb** [rii-mango/Papaya#209]
Hi,

I am using Flask to send a CT  (.nii.gz) from client to server using their (send_file() function) and I tried displaying that image with both approaches from docs:
```
params["files"] = [myFile];

params["binaryImages"] = [myArrayBuffer]; // single file
params["binaryImages"] = [[mySeriesAb1, mySeriesAb2, mySeriesAb3]];  // a DICOM series
```
Those didn't work, what am I missing?

**Comment by gaiborjosue** [comment]
Hello, @cosminbvb, did you find a solution?
