### ISSUE TITLE
Viewer position updated incorrectly 

### ISSUE THREAD

**Issue by pauldmccarthy** [rii-mango/Papaya#21]
Howdy,

I've noticed that in some circumstances when clicking on the viewer, the selected position is updated incorrectly. I've only observed this behaviour in Chrome (OSX Mavericks, Version 41.0.2272.3 dev (64-bit)).

More specifically, I've found that this occurs in two situations:

1. If a viewer is embedded within a `<div>` element, with CSS style `overflow: scroll`, and this div is scrolled down; for example:

        <div style="width: 550px; height: 400px; overflow: scroll">
          <div style="width: 500px; height: 500px;">
            <div class="papaya" data-params="params"></div>
          </div>
        </div>

2. If a nested viewer is embedded normally on a page, and the user scrolls down the page, and then increases/decreases the page zoom. This is observable on the 'lorem' demo: http://rii.uthscsa.edu/mango/lorem.html

I've personally fixed this by updating the cached `Viewer.canvasRect` attribute in `Viewer.updatePosition` (https://github.com/pauldmccarthy/Papaya/commit/2fb0c2fa8c5f9f6a6e32df7201d36a2d9e002374).

This patch seems to fix the issue for me. However, I don't know the Papaya codebase well enough to judge whether this is a viable solution for other platforms.

Cheers,

Paul

**Comment by rii-mango** [comment]
Thanks.  I can recreate the issue you describe.  Will fix...

**Comment by rii-mango** [comment]
This issue is fixed in the v0.7 release.  Thanks!
