### ISSUE TITLE
How to integrate Papaya in a React.js component?

### ISSUE THREAD

**Issue by Antonio-Riccelli** [rii-mango/Papaya#213]
Hi, 
As per title, I'm trying to implement Papaya viewer in my React.js frontend, but I'm struggling to figure out how. I've tried installing it via NPM as a standard package and following the basic examples provided there, but I'm unable to render anything. 

Has anybody implemented it in React successfully?

**Comment by hanayik** [comment]
Hi, openneuro.org used papaya successfully in the past, however they recently switched to NiiVue ( easily works with react despite the name). It's not associated with Vue. If you really want to see how to make papaya work in react then you could look through old versions of openneuro.orgs website code on GitHub. It might be worth trying NiiVue which is more actively maintained and developed. 

(For full disclosure, I'm one of the NiiVue developers, but we have contributed back to nifti-reader-js and other projects that the papaya Devs also created).

**Comment by Antonio-Riccelli** [comment]
@hanayik thank you so much for your answer! I'm going to have a look at both NiiVue and some older versions of openneuro.org. 
For now, I've tried running in a simple html/css/js app and it works fine, but it fails in React.

**Comment by Antonio-Riccelli** [comment]
For those who are interested, I've also found this: https://github.com/arindas/papaya-react
