### ISSUE TITLE
Voxel dimensions are not valid

### ISSUE THREAD

**Issue by khamael** [rii-mango/Papaya#22]
Does it support 4th dimension niftis? Like fMRI?

**Comment by khamael** [comment]
Ok, I see it supports, it was my .nii that didn't have the 4th dimension with a valid pixdim.
and, how do I switch between the different timepoints? the header correctlty says (1 of 31)..

**Comment by khamael** [comment]
and I take it back.. found it. my bad

**Comment by rii-mango** [comment]
No problem.  Glad you figured it out!
