### ISSUE TITLE
turn off mouse scroll event

### ISSUE THREAD

**Issue by agthumoe** [rii-mango/Papaya#24]
Is there any way to turn off mouse scroll event? It is nice to have that feature but I have an issue if I added two displays for example:
````
    <div class="papaya" data-params="params_1"></div>
    <div class="papaya" data-params="params_2"></div>
````
mouse scroll event only works with the first display. There is physical scroll bar under each display which can be used as an alternative. The issue with mouse scroll is that I can't scroll down the page to view the second display. So, if I can remove the mouse scroll event, I think that will solve the problem.

**Comment by rii-mango** [comment]
I've added a fix for this.  It was already designed to ignore scrolling when using more than one viewer, but the assumption was that the viewers were nested inside another div.  For example:

```javascript
<div class="smallViewer left">
    <div class="papaya" data-params="params1"></div>
</div>

<div class="smallViewer right">
    <div class="papaya" data-params="params2"></div>
</div>
```

Now it should ignore scrolling if more than one viewer is present with or without nesting.  I also added a new test for debugging issues when more than one viewer is used.  It's in tests/debug_server_nested.html
