### ISSUE TITLE
Open dicom

### ISSUE THREAD

**Issue by Khanshk** [rii-mango/Papaya#25]
Papaya is looking great.....
How to load images automatically from folder containing dicom images/series?
currently able to load single image.
var params = [];
params["images"] = ["data/.....?"];
let me know the possibility Thanks

**Comment by rii-mango** [comment]
Just create an array of all the files in the series.  The example below will load two series, each with three images:

```javascript
var params = [];
params["images"] = [["data/series1image1", "data/series1image2", "data/series1image3"],
    ["data/series2image1", "data/series2image2", "data/series2image3]];
```
