### ISSUE TITLE
Support for float64

### ISSUE THREAD

**Issue by chrisfilo** [rii-mango/Papaya#27]
Currently papay does not support displaying images with more than 4 bytes of data in each voxel. Support for float64 images (even through casting to float32) would be very appreciated!

**Comment by rii-mango** [comment]
It should now support float64.  I've had trouble finding 64-bit images to test with.  I only have a single big-endian 64-bit floating point image.  Please test with any images you have available, especially little endian.  Let me know if any don't work as expected.

**Comment by chrisfilo** [comment]
I tested it on other datasets and I works as advertized. Thanks!
