### ISSUE TITLE
Restart viewer

### ISSUE THREAD

**Issue by vsoch** [rii-mango/Papaya#31]
What is the javascript command to restart (eg, re-initialize the viewer) in the browser given updated parameters?

**Comment by vsoch** [comment]
Anybody out there??

**Comment by rii-mango** [comment]
You can try:
```
papayaContainers[0].viewer.resetViewer();
papayaContainers[0].toolbar.updateImageButtons();
papayaContainers[0].viewer.loadImage(["../data/myNewImage.nii.gz"], true)
```

See this example of how to restart the viewer and load a new image:
https://github.com/rii-mango/Papaya/issues/28

I'd like to add something to the API to do this more easily, since there have now been a couple of questions about it.

**Comment by vsoch** [comment]
Thank you! I literally haven't slept for 3 days trying to get a workaround solution for this, and you just solved the entire issue with three lines!!  

I'm going to run around the building and do some happy frolicking, then back to work :O)

**Comment by rii-mango** [comment]
Glad to have helped!  Like I said, I'll try to add some easier-to-use API calls in the future...

**Comment by rii-mango** [comment]
You can now restart a viewer like this:

`papaya.Container.restartViewer(index, refs, [forceUrl, [forceEncode]]);`

For example:

`papaya.Container.restartViewer(0, ["../data/myNewImage.nii.gz"], true);`

**Comment by vsoch** [comment]
Would this preserve the params specified? We have an issue where we specify parameters in advance for our maps, but then restarting the viewer loses all the params. Could we pass them in again?

**Comment by rii-mango** [comment]
Try this instead (note use of "reset", not "restart"):

```
papaya.Container.resetViewer(index);  // uses original params
papaya.Container.resetViewer(index, paramsNew);  // specify new ones
```

**Comment by vsoch** [comment]
Excellent! I will give this a try later today and post an update.

**Comment by vsoch** [comment]
This worked! It's working on my dev branch, and we should hopefully have the fix live soon. Thanks again!
