### ISSUE TITLE
Support for FileReader objects

### ISSUE THREAD

**Issue by vsoch** [rii-mango/Papaya#32]
Would this be possible? I am making an interface that will read [header info from a nifti](http://vsoch.github.io/nifti-drop/), and would like to have a nice viewer instead of my lame histogram :)  It would be something like:

      // Function to add / remove image from viewer
        function viewimage(nifti) {
        // Reset viewer and load new images
        papayaContainers[0].viewer.resetViewer();
        papayaContainers[0].toolbar.updateImageButtons();
        papayaContainers[0].viewer.loadBaseImage(["img/MNI152_T1_2mm_brain.nii.gz"],true)
        papayaContainers[0].viewer.loadOverlay([nifti.data],true)
       }

where `nifti.data` is a `Float32Array[902629]` or I could see something like:

      papayaContainers[0].viewer.loadOverlay([file],true)

where `file` is a fileReader object of some flavor.

**Comment by rii-mango** [comment]
Papaya will accept File objects.  If you have a File object, try passing it like this:

```
papayaContainers[0].viewer.loadBaseImage([myFileObj]);  // drop that second 'true' parameter
papayaContainers[0].viewer.loadOverlay([myFileObj]);
```

It then creates its own FileReader to process the Files.  The files would presumably come from a file selection dialog or drag/drop.

I could add a way for it to accept a raw ArrayBuffer, if that would be useful.  I'm not sure about a Float32Array (is that just image data?), but an ArrayBuffer of just raw bytes of the entire file.

**Comment by vsoch** [comment]
It worked!! So awesome! I will have something to show soon, latest tomorrow!

**Comment by vsoch** [comment]
[so cool!](http://vsoch.github.io/nifti-drop/)

**Comment by vsoch** [comment]
I found a bug with viewing an uncompressed nifti - am looking at now.

**Comment by vsoch** [comment]
Interesting, when it's an uncompressed nifti, Papaya says that "name" is undefined, specifically this name:

      with (typeof __commandLineAPI !== 'undefined' ? __commandLineAPI : { __proto__: null }) {
      papaya.viewer.ColorTable.OVERLAY_COLOR_TABLES.length]
      }

I will take a look again at this when I'm less tired - can you see the error in the console? Let me know if you have any ideas! The Papaya codebase is massive and I'm green when it comes to Javascript, so I'm a bit slow at figuring these things out. Thanks again for your help!

**Comment by vsoch** [comment]
ok, I have a fix that seems to work - I noticed that passing the command in with "false" and "false" AFTER the page loaded seemed to work for the uncompressed file, eg, this command:

         papayaContainers[0].viewer.loadOverlay([file],false,false);

so I added a timeout function:

        setTimeout(function(){
              papayaContainers[0].viewer.loadOverlay([file],false,false);
         }, 500);

The interesting thing is that if I tweak the time to 200ms, it works locally but not on the gh-pages. 500ms seems to work, although I'm concerned that larger images might need more of a delay. This is strange! I'm looking forward to hearing your thoughts - I think it's related to the timing of events / order of operations of things. I'm just starting to get my head around callback functions, etc.

**Comment by rii-mango** [comment]
Looks cool!  Is it possible to post a version of your tool that demonstrates the bug?  I am not able to recreate it.  I agree that adding a timeout is not a good long-term solution.

**Comment by vsoch** [comment]
Done! [Look here](http://vbmis.com/bmi/project/papaya/) - it's exactly the same but without the timeout added. Let me know if you figure anything out, or learn anything, I really like tracking these things down! :)

**Comment by vsoch** [comment]
And to verify - to produce the bug, try loading a zipped vs. unzipped nifti. Here are the files that I am testing with:

[compressed](http://www.vbmis.com/bmi/project/papaya/mr/beta_0001.nii.gz)
[uncompressed](http://www.vbmis.com/bmi/project/papaya/mr/motor_lips.nii)

**Comment by rii-mango** [comment]
Since it loads asynchronously, making calls like this won't work:
`````
papayaContainers[0].viewer.loadBaseImage([myFileObj]);
papayaContainers[0].viewer.loadOverlay([myFileObj]);
`````
The second file will begin loading before the first one has finished.  The best thing to do is to use the `resetViewer` method (which will use a `loadNext()` callback each time an image has finished loading).  It didn't support File objects before, but I just added a fix for this.  Try something like this:

```
var params = [];
params.files = [];
params.files[0] = myFile1;
params.files[1] = myFile2;
// add other parameters...

papaya.Container.resetViewer(0, params);
```
I can't say 100% that this will fix the issue for you.  But I was able to create an example to mimic what I think is going on and this fixed it for me.  Give it a try...

**Comment by vsoch** [comment]
This doesn't work for me - if I don't completely re-initialize the params, then the viewer does show up again (albeit a smaller size) but none of my nifti files load. Do you have the example anywhere so I can look at the details? I'll give it a try again tomorrow morning, definitely not giving up on this!

I have a separate question I'll post to another issue soon - basically I have the canvas exporting to an svg png that shows in a pop up window (so I can right click --> save as) but the overlay colors aren't showing up! Are they part of the canvas or something else?

**Comment by vsoch** [comment]
A quick update! I (mostly) figured out the canvas part, still working on the first part! :)

**Comment by vsoch** [comment]
Canvas export to png is working!!

![working](https://cloud.githubusercontent.com/assets/814322/10124303/b1acf7de-6506-11e5-823a-29f7d3fb7e81.png)

**Comment by rii-mango** [comment]
Were you ever able to get this working the way you needed?  I've somewhat lost track of what the issue was here... reusing File objects to re-initialize a viewer?

**Comment by vsoch** [comment]
Yep :)

http://vsoch.github.io/nidmviewer/examples/

Hopefully soon we will have something like this integrated into Neurovault:

https://github.com/NeuroVault/NeuroVault/pull/354

**Comment by rii-mango** [comment]
That looks awesome!  Let me know if you need any other changes or run into other issues...

**Comment by spiropan** [comment]
Dear @vsoch and @rii-mango 
I am working with Papaya and would love to add screenshot functionality (i.e. export current image overlays, cursor position and thresholds to png) and I come across this thread. Vanessa in your comment on September 27, 2015 it appears you were able to accomplish this? If you have ready access to the code snippet or another link with more info I would greatly appreciate it. I haven't been able to find much on the web after extensive searching. Also please let me know if I should add this as an issue or requested feature to the repository? Many thanks in advance! Spiro

**Comment by vsoch** [comment]
I'm no longer with the lab and haven't updated the viewer since a little after this post, but a quasi working version (that should at least get you the functionality that you need is here --> http://neurovault.org/collections/1692/fsl_contrast_mask.nidm I would adapt for a more up to date version of papaya, which definitely has more cool features since that was coded up!

**Comment by spiropan** [comment]
Very cool, will check it out. Thanks so much for your prompt reply!

**Comment by spiropan** [comment]
Hi Vanessa,

I've managed to locate the export_svg() function. It references
a CanvasToSVG function, but I can't seem to locate the code for it in the
web source files. Online I came across the below project:

https://github.com/gliffy/canvas2svg

Do you remember if this is what you used (if not, no worries, I realize
it's been a while)? Given that the cases don't match I'm inclined to say
no...
Thanks again,
Spiro

**Comment by spiropan** [comment]
Ah, thanks for the tip! It was tucked away in one of the minified files..I
wonder how my index search over the whole folder missed it, I must not have
registered the extension or something...

**Comment by spiropan** [comment]
Cool, so in the current Papaya version I can access the
papayaContainer[0].viewer.canvas.toDataURL function which should do what I
need. Your files helped me organize my thoughts as well.
Thanks again for your help and for your replies!

**Comment by vsoch** [comment]
Anytime! :O)
