### ISSUE TITLE
"RangeError: Invalid typed array length" when using a FLOAT64 file

### ISSUE THREAD

**Issue by chrisfilo** [rii-mango/Papaya#33]
File in question:
http://neurovault.org/media/images/845/EMO_SOC.nii.gz

Stacktrace:

	Uncaught RangeError: Invalid typed array length
	papaya.volume.ImageData.readFileData @ papaya.js:786
	papaya.volume.Volume.finishedReadImageData @ papaya.js:910
	(anonymous function) @papaya.js:752
	papaya.volume.nifti.HeaderNIFTI.readImageData @ papaya.js:798
	papaya.volume.Header.readImageData @ papaya.js:780
	papaya.volume.Volume.finishedReadHeaderData @ papaya.js:909
	(anonymous function) @ papaya.js:752
	papaya.volume.Header.onFinishedHeaderRead @ papaya.js:780
	(anonymous function) @ papaya.js:752
	papaya.volume.nifti.HeaderNIFTI.readHeaderData @papaya.js:798
	papaya.volume.Header.readHeaderData @ papaya.js:776
	papaya.volume.Volume.finishedReadData @ papaya.js:908
	(anonymous function) @ papaya.js:907

**Comment by rii-mango** [comment]
Should be fixed now.

**Comment by chrisfilo** [comment]
this worked - thanks!
