### ISSUE TITLE
Dynamic movement of x y z coordinates

### ISSUE THREAD

**Issue by vsoch** [rii-mango/Papaya#35]
is there a way to dynamically (with jquery/javascript) move the position of the crosshair for the user? I'm poking around all the different papayaContainer[0].viewer functions, but haven't found anything yet. I have a feeling the answer to this is an easy one!

**Comment by rii-mango** [comment]
Depending on what "space" you are in...

This will move the current coordinate to (10, 10, 10) based on indices from the left/anterior/superior corner of the image.
```
var coor = new papaya.core.Coordinate(10, 10, 10);
papayaContainers[0].viewer.gotoCoordinate(coor);
```

This will move the current coordinate to (10, 10, 10) based on millimeters from the origin.
```
var coor = new papaya.core.Coordinate();
papayaContainers[0].viewer.getIndexCoordinateAtWorld(10, 10, 10, coor);
papayaContainers[0].viewer.gotoCoordinate(coor);
```

Note, if you all you want to do is set an initial coordinate, you can do this:
```
params["worldSpace"] = true; // or false as above
params["coordinate"] = [10, 10, 10];
```

**Comment by vsoch** [comment]
Awesome! I can't wait to add this :O)  Thanks as always for your prompt help, and Papaya in general... it's a fantastic tool and makes possible these projects.

**Comment by vsoch** [comment]
Ok, we have dynamic coordinate browsing added to nifti-drop!

![image](https://cloud.githubusercontent.com/assets/814322/10143445/46404efc-65cd-11e5-932d-e245297cadf6.png)

Wicked cool! Thanks for your help!
