### ISSUE TITLE
Help! please! About problem viewing dicom file

### ISSUE THREAD

**Issue by chien-vu** [rii-mango/Papaya#38]
Hello everyone, 
I have a link https://github.com/mi-kas/DICOMcoffee ( demo http://chienvu.esy.es/DICOMcoffee-master/)
Author of this project is @mi-kas. I'm interested in this project. I have tried to open dicom files on this demo, but i can't see any picture. The viewer is still black. I don't know why this project run wrong. 
Can you help me to fix it? 
Thank you so much!!!!! 
Chienvu

**Comment by rii-mango** [comment]
Hi.  The project you link to doesn't appear to have anything to do with Papaya.  Although, you are welcome to try the Papaya Viewer demo here, which supports many types of DICOM including compressed: http://rii.uthscsa.edu/mango/papayabeta/
