### ISSUE TITLE
Change "close overlay" to hide/show overlay

### ISSUE THREAD

**Issue by bcipolli** [rii-mango/Papaya#40]
There's no way to hide/show overlay. When I press the "close overlay" button, not only is the overlay hidden, but the entire tool disappears.

It'd be great to have a hide/show overlay option.

Originally opened here:
https://github.com/NeuroVault/NeuroVault/issues/399

**Comment by bcipolli** [comment]
Perhaps `removeOverlay` could be set to `toggleOverlay`? Any concerns with such an approach?
https://github.com/rii-mango/Papaya/blob/7d8875fe21f1ffb2f6d0205a9788b233f135bcfa/src/js/viewer/viewer.js#L2735

**Comment by rii-mango** [comment]
I've added a "Hide/Show Overlay" option.  Please check it out.

![screen shot 2016-01-04 at 10 26 12 am](https://cloud.githubusercontent.com/assets/1859709/12094343/a8e8eca6-b2cd-11e5-8166-f7948ad6ebb0.png)

**Comment by kapilvirasat** [comment]
Hello @rii-mango 
Can we add hide overlat from code means pass configuration and hide the overlay. Students needs to guess the overlay.

```
// Pass some code here to hide the overlay by default or make it transparent (instead from menu)
var params = [];
            params["worldSpace"] = true;
            params["images"] = [currentImg, overlayImg];
            papaya.Container.syncViewers = true;
            params[overlayImg] = {"min": 4, "max": 8};
            params[currentImg, overlayImg] = {"min": 4, "max": 8, "lut": "Red Overlay"};

```
