### ISSUE TITLE
Stand alone nifti parser

### ISSUE THREAD

**Issue by NicolasRannou** [rii-mango/Papaya#41]
Is there a good way to use the Nifti parser as a stand alone project?

I am playing around with it as I want to parse/visualize Nifti datasets on my own but it seems tightly integrated into Papaya.

Thanks!

**Comment by rii-mango** [comment]
I can probably release it as a separate project.  I'll look into this...

**Comment by chrisfilo** [comment]
We have been using (and contributing to) this one https://github.com/scijs/nifti-js so far. It might be a source of inspiration or maybe the two projects could join. @constellates

**Comment by rii-mango** [comment]
I figured there must be a NIFTI-JS implementation out there by now.  @NicolasRannou the above linked library may be more robust than what's in Papaya.  I'll also look into the possibility of replacing/merging Papaya's NIFTI code with that library...

**Comment by NicolasRannou** [comment]
Thanks, I checked it out in the past but I thought it was a dead project (2 commits in 2014 and 2 in 2015) whereas Papaya is very active.

Only limitation with nifti-js is that is doesn't parse the sform.

Does Papaya parse the sform transform?

**Comment by rii-mango** [comment]
Yes, it is stored in `affine` in [nifti.js](https://github.com/rii-mango/Papaya/blob/master/src/js/volume/nifti/nifti.js#L148).

**Comment by rii-mango** [comment]
Started [this](https://github.com/rii-mango/NIFTI-Reader-JS), but there's still more [todo](https://github.com/rii-mango/NIFTI-Reader-JS/wiki/TODO).

**Comment by NicolasRannou** [comment]
Thanks!
