### ISSUE TITLE
Error opening certain DICOM files

### ISSUE THREAD

**Issue by okrad** [rii-mango/Papaya#42]
I'm having issues opening certain DICOM files, which I can open with Osirix or Ginkgo CADx with no errors.

In chrome I get an error: ```daikon.js:427 Uncaught TypeError: Cannot read property '0' of undefined```

The problem seems to be located in method ```quantizeAndInverse```: ```component.quantizationTable``` seems to be undefined.

Attached is one example file causing the problem.

Thank you for your great job!

[20160118.dcm.zip](https://github.com/rii-mango/Papaya/files/95848/20160118.dcm.zip)

**Comment by NicolasRannou** [comment]
Daikon doesn't support this compression scheme. (JPEGBaseline)

**Comment by rii-mango** [comment]
It is suppose to support 8-bit JPEG Baseline, but not 12-bit.  (Although I've found relatively few images of this transfer syntax to test with.)  

That image is 8-bit JPEG Baseline (1.2.840.10008.1.2.4.50).

It uses [jpgjs](https://github.com/notmasteryet/jpgjs) for JPEG Baseline support.  I'll look into this...

**Comment by NicolasRannou** [comment]
Ah yes I misread the Daikon README...

**Comment by NicolasRannou** [comment]
FYI - @chafey solved it in cornerstone wado-image-loader:
https://github.com/chafey/cornerstoneWADOImageLoader/tree/master/src/decoders
https://github.com/chafey/cornerstoneWADOImageLoader/blob/master/src/decoders/decodeJPEGBaseline.js
https://github.com/chafey/cornerstoneWADOImageLoader/blob/master/src/decoders/external/jpeg.js

**Comment by okrad** [comment]
Ok, thank you for looking into this...

**Comment by rii-mango** [comment]
Thanks for the heads up about the new version of the decoder.  It does appear to have a few bug fixes as well as support for 12-bit JPEG Baseline.  The license is compatible with Daikon, so I've replaced the old jpgjs lib with it.  It should now load your file.
