### ISSUE TITLE
Crashes in chrome, Firefox unresponsive with big files

### ISSUE THREAD

**Issue by okrad** [rii-mango/Papaya#43]
Trying to open the attached file in chrome (>= 47) results in a crash. Firefox (>= 42) is very slow and becomes unresponsive for a while, but then it is able to open the image, leaving however the viewer in an unusable state.

I understand that the file is quite big, but dealing with such big images is not so uncommon.

[crash_chrome.dcm.zip](https://github.com/rii-mango/Papaya/files/101131/crash_chrome.dcm.zip)

**Comment by okrad** [comment]
That's really impressive, thank you for pointing it out. I will surely give it a try, but as you said the purpose of that project is quite different.
Do you know of any plans on switching to opengl in papaya?

**Comment by rii-mango** [comment]
Archiving this.  Not able to reproduce.
