### ISSUE TITLE
Pixel value 

### ISSUE THREAD

**Issue by jongo** [rii-mango/Papaya#45]
Hi,

When displaying pixel value on DICOM images (in radiological mode) are you always using this line:

`if (this.usesGlobalDataScale) {
        value = (this.checkSwap(this.imageData.data[offset]) * this.globalDataScaleSlope) +
            this.globalDataScaleIntercept;
    }`

This means that you always showing HU if slope and intercept are present.

[voxelvalue.js](https://github.com/rii-mango/Papaya/blob/198b34979c5b077e5d4c66061d1e2da725aba36a/src/js/volume/voxelvalue.js)

Regards,
Jongo

**Comment by rii-mango** [comment]
Yes, it should always be using the slope and intercept if present.  **However**, I just fixed a bug that was causing the slope and intercept to be missed in the case of "enhanced" DICOM formats.  Not sure if this matters for your question.

You can try it here: http://rii.uthscsa.edu/mango/papayabeta/

**Comment by jongo** [comment]
Thanks for answer!
I was using "normal" DICOM images, so that bug wasn't my case. Anyway, good that it is fixed now.
