### ISSUE TITLE
Oblique MPR

### ISSUE THREAD

**Issue by jongo** [rii-mango/Papaya#46]
Hi,

Papaya currently supports orthogonal mpr only. Do you have plans to support oblique (non-orthogonal) mpr. If so what is the time frame to expect it?

Regards,
Jongo

**Comment by rii-mango** [comment]
Oblique plane is pretty much just missing UI controls.  There's already support for it in the code.  You can play with it by editing`mat` in [transform.js](https://github.com/rii-mango/Papaya/blob/master/src/js/volume/transform.js#L369).  For example:

```
papaya.volume.Transform.prototype.updateTransforms = function (mat) {
    this.mat = [[.7071, -.7071, 0, 91.11], [.7071, .7071, 0, -28.95], [0, 0, 1, 0], [0, 0, 0, 1]];

    this.updateSizeMat();
    this.updateOrientMat();
    this.updateOriginMat();
    this.updateIndexTransform();
    this.updateMmTransform();
    this.updateWorldMat();
};
```

![screen shot 2016-02-05 at 10 16 44 am](https://cloud.githubusercontent.com/assets/1859709/12851821/9467f622-cbf1-11e5-9359-3f8a050c3f01.png)

I'll try to add controls for it soon.

**Comment by jongo** [comment]
Great! Oblique MPR will drastically increase usability! I will play with it. Really looking forward to it!

**Comment by jongo** [comment]
I was looking at [ClearCanvas ](https://github.com/ClearCanvas/ClearCanvas)MPR, and they have added lines that represent planes which can be moved and rotated. Maybe it will help you.

Cheers!

![image](https://cloud.githubusercontent.com/assets/1005993/12881322/5529b8c4-ce49-11e5-83a3-80dd2c9c228e.png)
