### ISSUE TITLE
Window level values

### ISSUE THREAD

**Issue by jongo** [rii-mango/Papaya#47]
Hi,

When I compare Papaya window level values (small grayscale panel box) when working with DICOM images, they are different then window level values presented in other DICOM viewers. Why is that difference?

Regards,
Jongo

![papaya1](https://cloud.githubusercontent.com/assets/1005993/12817348/d4a590be-cb51-11e5-9cb4-5ef91f493410.jpg)
![clearcanvas](https://cloud.githubusercontent.com/assets/1005993/12817350/d758d7f8-cb51-11e5-9526-e12ae7a8b57a.jpg)

**Comment by rii-mango** [comment]
It is just a different representation of the same values.  Papaya gives the "display range".  The minimum value represents black (anything <= this value is black) and the max value is white (anything >= this value is white).

min = center - (width / 2) = 50 - (350 / 2) = -125
max = center + (width / 2) = 50 + (350 / 2) = 225

**Comment by jongo** [comment]
Thanks!
