### ISSUE TITLE
wishlist: support of "<type>Statistic</type>" FSL atlases

### ISSUE THREAD

**Issue by yarikoptic** [rii-mango/Papaya#5]
So I have built it adding "-atlas /usr/share/fsl/data/atlases/NeuroSynth-525-posterior_z.xml " on a NeuroDebian box to enable NeuroSynth atlas to see how well it would work.  Unfortunately it didn't (see below) and I remembered that I had to patch fslview to support this kind of generalization over their original "Probabilistic" atlases.   Original discussion/patch happened on the FSL list and I was promised that the patch will be included in the next release of FSLview whenever it eventually comes out https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1309&L=fsl&D=0&P=11451  so I guess it should be safe to rely upon it

```
Uncaught TypeError: Cannot call method 'getVoxelAtCoordinate' of null papaya.js?version=0.6.2&build=509:22
papaya.volume.Volume.getVoxelAtCoordinate papaya.js?version=0.6.2&build=509:22
papaya.viewer.Atlas.getLabelAtCoordinate papaya.js?version=0.6.2&build=509:22
papaya.viewer.Display.drawDisplay papaya.js?version=0.6.2&build=509:22
papaya.viewer.Viewer.updateCursorPosition papaya.js?version=0.6.2&build=509:22
papaya.viewer.Viewer.mouseMoveEvent papaya.js?version=0.6.2&build=509:22
(anonymous function)
```

**Comment by rii-mango** [comment]
Archiving this.  Out of scope for now.
