### ISSUE TITLE
Oblique mpr ui controls

### ISSUE THREAD

**Issue by jongo** [rii-mango/Papaya#51]
Hi again!

You showed that there is an oblique plane MPR support already in the Papaya code https://github.com/rii-mango/Papaya/issues/46, and that it is missing UI controls at the moment. Do you have some short term plans to implement oblique MPR UI controls, as it is really useful feature?

**Comment by rii-mango** [comment]
I'm currently working on adding GUI controls for lots of features, so that should be included in that effort.  I'm hoping that it will be done within the next couple of weeks.

**Comment by rii-mango** [comment]
This feature has been added.  Please check it out: https://github.com/rii-mango/Papaya/wiki/User-Interface-Features#rotation

![image](https://cloud.githubusercontent.com/assets/1859709/14572687/bb19dd66-0315-11e6-8cfb-9ba97a710083.png)

You can also set a transform via the loading params, such as:

```javascript
params["rotation"] = [0,0,45];
params["rotationPoint"] = "center";
```

**Comment by jongo** [comment]
Great, it works perfectly, just what I asked! This feature is very useful for radiologists. 

Just a note here: radiologists usually manipulate oblique MPR by moving (rotating) intersection lines, and not images.

**Comment by rii-mango** [comment]
Good point about the UI.  Will look into it...
