### ISSUE TITLE
ImageToWorld transform

### ISSUE THREAD

**Issue by NicolasRannou** [rii-mango/Papaya#52]
Can we display the image to world transform for the image somehow?
Does nifti-reader-js take care of it or does Papaya do?

I am trying to get the transform for this file:
https://drive.google.com/file/d/0B2-PspfnvPNgY1R2SFFTd3YtaGM/view?usp=sharing

but I get inconsistent results between Slicer, nibabel, etc.

Best,

**Comment by rii-mango** [comment]
The qform in that image, converted to a 4x4 is:
```
-0.859375 0 0 49.84375
0 0.859375 0 -67.890625
0 0 0.859375 -53.7109375
0 0 0 1
```

There's no way from the GUI in Papaya to see the qform as a 4x4, but in nifti-reader-js you can use `nifti.NIFTI1.prototype.getQformMat()` to convert it.
