### ISSUE TITLE
freesurfer custom color table 

### ISSUE THREAD

**Issue by akeshavan** [rii-mango/Papaya#55]
I want to create a custom colormap for the freesurfer aparc+aseg file. I have a dictionary that maps voxel values to rgb colors, but the custom colormap function (lookupRed, lookupGreen...) has inputs that are normalized to 0-255. Is it possible to access the un-normalized value of the voxel in these methods?

**Comment by rii-mango** [comment]
Sorry for the late reply.  I modified the custom lookup table to take two arguments: `screenVal` and `imageVal`.  `imageVal` will be the raw, non-normalized image values.

Updated documentation: https://github.com/rii-mango/Papaya/wiki/How-To-Make-a-Color-Table

**Comment by akeshavan** [comment]
Thanks! However, I'm getting null for imageVal at the moment

**Comment by rii-mango** [comment]
Be sure you're using the latest build.  There can always be some kind of bug I'm missing, but it appears to be working for me.  Here's an example that colors any screen pixel red when the image voxel value is greater than 8.

```html
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="../release/current/standard/papaya.css" />
    <script type="text/javascript" src="../release/current/standard/papaya.js"></script>

    <script type="text/javascript">
        var myCustomColorTable = function() { };

        myCustomColorTable.prototype.lookupRed = function (screenVal, imageVal) {
            if (imageVal > 8) return 255; else return 0;
        };

        myCustomColorTable.prototype.lookupGreen = function (screenVal, imageVal) {
            return 0;
        };

        myCustomColorTable.prototype.lookupBlue = function (screenVal, imageVal) {
            return 0;
        };

        var params = [];
        params["images"] = ["data/zstat1.nii.gz"];
        params["zstat1.nii.gz"] = {lut: new myCustomColorTable()};
    </script>

    <title>Papaya</title>
</head>

<body>
    <div class="papaya" data-params="params"></div>
</body>

</html>
```

**Comment by akeshavan** [comment]
it works! thanks!

**Comment by seldamat** [comment]
This was super helpful for getting the Freesurfer LUT to display on Papaya. Thanks. However, I was curious to know if there is any easy way of getting the FreeSurfer labels to show up in the display as the user moves the cursor.

Do you need to build an xml file for that? And if so, how do you define the x,y,z coordinates?

**Comment by martinezmj** [comment]
This might help: https://github.com/rii-mango/Papaya/wiki/How-To-Use-Atlases
