### ISSUE TITLE
Image area getting cut

### ISSUE THREAD

**Issue by idmpacs** [rii-mango/Papaya#57]
Image rotation works very well, except that the part of the image area gets cut even when there is enough space to show it. Can you please fix this ?

![mpr](https://cloud.githubusercontent.com/assets/12911306/15352337/57730db8-1d01-11e6-834c-cf2ca04bc8bd.png)

**Comment by rii-mango** [comment]
Try using the new parameter `padAllImages`.  It should pad the data such that all three dimensions are the same size (regardless of voxel size).  This should avoid the unexpected black bands above and below the smaller dimensions of the original image.

`params["padAllImages"] = true;`
