### ISSUE TITLE
Ultimate visualization of statistical maps

### ISSUE THREAD

**Issue by chrisfilo** [rii-mango/Papaya#59]
A few years ago a very interesting visualization of statistical maps was proposed (see: http://mialab.mrn.org/datavis/index.html)

![sample_aod](https://cloud.githubusercontent.com/assets/238759/15596947/6a2b7104-2380-11e6-9670-485e47d3aec9.JPG)

It allows researchers to see the thresholded version of the map (the outline), effect size (hue), and confidence (absolute t value) at the same time. In context of Papaya this functionality could be broken down into two components:
- [ ] displaying outlines of a binary mask image (in this example it would be the excursion set produces by an inference technique)
- [ ] using an additional image (in this case it would be the t map) to control transparency of the overlay at each voxel

I know this is a lot to ask, but since we are scanning for longer and using bigger sample sizes displaying unthresholded statistical maps becomes more and more important. This would be a fantastic addition to Papaya!

**Comment by rii-mango** [comment]
This should be possible.  The binary mask may not work out nicely when the overlay is being interpolated into the space of the base image though.  It might look nicer to scan the displayed slices for above-threshold clusters and then draw the threshold line dynamically (as vector rather than raster data).

Do you have any example data?  Has there been any attempt to create a file format for this type of data (e.g., nifti file with two series points)?

**Comment by chrisfilo** [comment]
Thanks for looking into this!

1. I agree that generating the threshold line as a vector. It's worth noting that the mask file should still be a source of this line (most neuroimaging inference methods do not rely on simple voxelwise thresholding, but use things such as cluster size as well, thus to show the excursion set to depict what is statistically significant and what is not).

1. Here are some example files:
    1. Excursion set (for generating the threshold line): http://neurovault.org/collections/1111/spm_example.nidm/ExcursionSet.nii.gz
    1. T map (its absolute value defines the transparency of each overlay voxel): http://neurovault.org/collections/1111/spm_example.nidm/TStatistic.nii.gz
    1. Beta map (defines the hue of each overlay voxel): http://neurovault.org/collections/1111/spm_example.nidm/Contrast.nii.gz

1. Re: file format. Indeed, there is a file format for capturing results of statistical modeling and inference. It's called [NIDM-Results](http://nidm.nidash.org/specs/nidm-results_120.html) and includes all of the information (and more) to create such figure. It's rather complicated in nature (consist of a [.ttl](http://neurovault.org/collections/1111/spm_example.nidm.ttl) file describing metadata and relevant nifti files all zipped up). Here's an example of such file: http://neurovault.org/collections/1111/spm_example.nidm.zip. It would be great if Papaya supported .nidm.zip files, but that could take some time to implement.

**Comment by jbpoline** [comment]
This would be a great display, truly useful.
Could be combined with colormap recently proposed in matplotlib:
http://matplotlib.org/style_changes.html

**Comment by rii-mango** [comment]
Archiving this.  Out of scope for now.
