### ISSUE TITLE
Q: how could we enable 3d view same on the Readme example image

### ISSUE THREAD

**Issue by marlocorridor** [rii-mango/Papaya#61]
![3d image](https://camo.githubusercontent.com/b9b4bd8f9a07082bd4fc55616da254101815e470/68747470733a2f2f7261772e6769746875622e636f6d2f7269692d6d616e676f2f5061706179612f6d61737465722f646f63732f696d616765732f73706c617368322e706e67)

**Comment by rii-mango** [comment]
Papaya currently supports GIFTI (.surf.gii) and Mango (.surf) surface formats (links to more info about these formats [here](https://github.com/rii-mango/Papaya/wiki/Supported-Formats)).  Currently, you need to create the surface format file beforehand -- this is, Papaya does not generate the surface from the image file automatically.

To create a surface file, you can use Mango: http://rii.uthscsa.edu/mango/mango.html

Load your image in Mango, then go to Image > Build Surface.  You can adjust build parameters, such as threshold.  When the surface looks like what you want, in the surface viewer go to File > Save As.

More info about loading surfaces in Papaya: https://github.com/rii-mango/Papaya/wiki/Configuration#surfaces

**Comment by rii-mango** [comment]
P.S.  In the project, you can run tests/debug_server_surface.html to see the example in that screenshot.

**Comment by marlocorridor** [comment]
I get it now. Thanks.

By the way, these info are not in the wiki yet right? :)

**Comment by rii-mango** [comment]
There is some info here: https://github.com/rii-mango/Papaya/wiki/Configuration#surfaces

But as always, the documentation could be better...

**Comment by cancan101** [comment]
Are you saying that volume files (e.g. nifti files) cannot be viewed with the 3D viewer unless they are converted to surface files?

**Comment by martinezmj** [comment]
Yes, the viewer does not automatically convert the volumetric data to surface data.  You'll need the GIFTI equivalent of the NIFTI data.  It would be nice to add this feature, but at least for now, you need the surface data ahead of time.

**Comment by niks2060** [comment]
Hello Martin,
Any possibility of this feature to be introduced..?
If it will then most of the issue is solved.

**Comment by rjsgml5698** [comment]
How to add the colors?

**Comment by martinezmj** [comment]
@rjsgml5698 The surface data file itself may contain colors in the form of a RGB triplet per vertex.  Both GIFTI and Mango surface formats support this.   If all you need is to specify one solid color for the entire surface, you can do this:

`params["mySurface.surf.gii"] = {color: [1, 0, 0], alpha: 0.5};`

**Comment by rjsgml5698** [comment]
I really appreciate it. I understood and it worked. Do you have any plans to make React.js?
