### ISSUE TITLE
Need option to view only Axial, Coronal or Sagittal view

### ISSUE THREAD

**Issue by idmpacs** [rii-mango/Papaya#64]
It would be great to have option to view single Axial, Coronal or Sagittal View in the viewer. Currently you can change initial slice direction of MainView but still it makes sense to have single viewing plane as that would make more area available for viewing image.
The user should be able to scroll slices as well as switch view with space bar.

**Comment by rii-mango** [comment]
I think this is what you're looking for: `params["orthogonal"] = false;`

That will turn off the two smaller orthogonal slices, leaving only the main slice view.
