### ISSUE TITLE
Using papaya in a commercial website

### ISSUE THREAD

**Issue by Jagirhussan** [rii-mango/Papaya#65]
Hi,
    I would like to know if there are restrictions to use papaya in a commercial (non-research, non-educational) website. I plan to use it to render 3D images. 

Thanks
Jagir

**Comment by rii-mango** [comment]
There are no restrictions for use in commercial software.  It is MIT licensed.

**Comment by Jagirhussan** [comment]
Thank you very much for the prompt response. Much appreciated.
