### ISSUE TITLE
Having trouble creating new papaya viewer dynamically.

### ISSUE THREAD

**Issue by constellates** [rii-mango/Papaya#67]
I'm working on incorporating papaya into a site and would like to be able to create a new viewer and load an image when a user clicks a button.

I can get Papaya to work when I specify the papaya div in static html but I'm having difficulty when using a papaya div created by javascript.

So far when a user clicks a button I create a new papaya div

    <div class="papaya" data-params="params"></div>

I am then calling reset viewer after a timeout. The timeout may not be totally necessary, but for now I'm using it to ensure the above div has rendered.

    setTimeout(() => {
        var params = [];
        params["worldSpace"] = true;
        params["fullScreen"] = false;
        params["allowScroll"] = false;
        params["fullScreenPadding"] = false;
        params["images"] = ["/path/to/my/scan.nii.gz"];
        papaya.Container.resetViewer(0, params);
    },2000);

and I get the following error

    Uncaught TypeError: Cannot read property 'viewer' of undefined

I'm guessing this is caused by not being able to find a papayaContainer because if I log papayaContainers in the above block I get an empty array.

Is there a step I'm missing to initialize my div as a papayaContainer?

**Comment by constellates** [comment]
Update. I was able to get the viewer loading dynamically by calling

    papaya.Container.startPapaya();

after the div is rendered. Is this a reasonable way to dynamically create a container or is there a better way?

**Comment by rii-mango** [comment]
Yes, this is perfectly fine.  Another option:

```
papaya.Container.addViewer("myDivId", myParams);
```

I've added both addViewer() and startPapaya() to the API here: https://github.com/rii-mango/Papaya/wiki/API

**Comment by constellates** [comment]
Awesome. And the API document looks helpful for this issue now. Thanks.
