### ISSUE TITLE
Save image in jpeg or PNG

### ISSUE THREAD

**Issue by renardfe** [rii-mango/Papaya#69]
Hi,

I am interested to add a button to give the possibility to save the current view of Papaya in JPEG or PNG format (like a screen shot of papaya viewer). I try to find such command in the API, but I don't see anything closed to this subject. Is there a possibility to save the view in image file?

Thanks!

**Comment by rii-mango** [comment]
Yes, you can do:

```
window.open(papayaContainers[0].viewer.canvas.toDataURL("image/png"));
```

This will open a new window with the screenshot, which you can then right-click to save.  If you want to create a button that will save it automatically, see this: http://stackoverflow.com/questions/17397319/save-canvas-as-jpg-to-desktop

**Comment by MarlonLiu1991** [comment]
I have tried  to add this code "window.open(papayaContainers[0].viewer.canvas.toDataURL("image/png")); " , but an error occured: "Uncaught TypeError: Cannot read property 'canvas' of undefined". Why?

**Comment by joweste** [comment]
I have the same problem.
Is there some news to solve it?
