### ISSUE TITLE
Multiple images are not in order

### ISSUE THREAD

**Issue by dpaniukov** [rii-mango/Papaya#75]
Hello,

When I try to show multiple images with `params["images"] = ["data/myBaseImage.nii.gz", "data/myOverlayImage.nii.gz"];`, sometimes the base image overlays the other image. If I rerun the script, it may or may not show the overlaid image on top of the base image. 

Any thoughts how to fix it?

**Comment by martinezmj** [comment]
I've never heard of this happening before.  It sounds like a race condition, but I don't think that's possible.  The triggering of loading an overlay happens only once the base image loading has completed.

Can you share your "params" configuration?

**Comment by dpaniukov** [comment]
Hello, frankly I'm using this software on jupyter notebooks: https://github.com/akeshavan/nbpapaya that utilizes Papaya.
I mistakenly assumed that the condition race was generated on the Papaya side.
For instance, when I use: Brain(["/path/to/brain1.nii","/path/to/brain2.nii"],8888)
My bad. I'll contact the author of the nbpapaya. Or just fix it myself. 

Thanks for your clarification!

**Comment by rii-mango** [comment]
No problem.  Thanks!
