### ISSUE TITLE
Viewing DICOM Series in a viewer

### ISSUE THREAD

**Issue by ali-muhammad** [rii-mango/Papaya#76]
I have an array that contains the list of DICOM Series. I want to view it on the viewer through params when a button is clicked. Is there a way that I can view that series either by params or any other way ?

**Comment by martinezmj** [comment]
See the API documentation there: https://github.com/rii-mango/Papaya/wiki/API

See the below example.  If you want to reload the viewer, see the resetViewer() function.  If you want to add an overlay image, see the addViewer() function.
```javascript
    <script type="text/javascript">
        var params = [];
        params["images"] = ["data/sample_image.nii.gz"];
        params["atlas"] = "MNI (Nearest Grey Matter)";

        var params2 = [];
        params2["images"] = [["data/dicom/brain_001.dcm", "data/dicom/brain_002.dcm", "data/dicom/brain_003.dcm",
            "data/dicom/brain_004.dcm", "data/dicom/brain_005.dcm", "data/dicom/brain_006.dcm",
            "data/dicom/brain_007.dcm", "data/dicom/brain_008.dcm", "data/dicom/brain_009.dcm",
            "data/dicom/brain_010.dcm", "data/dicom/brain_011.dcm", "data/dicom/brain_012.dcm",
            "data/dicom/brain_013.dcm", "data/dicom/brain_014.dcm", "data/dicom/brain_015.dcm",
            "data/dicom/brain_016.dcm", "data/dicom/brain_017.dcm", "data/dicom/brain_018.dcm",
            "data/dicom/brain_019.dcm", "data/dicom/brain_020.dcm"]];

        function resetViewer() {
            papaya.Container.resetViewer(0, params2);
        }

        function addViewer() {
            papaya.Container.addImage(0, params2["images"][0]);
        }
    </script>
```

**Comment by ali-muhammad** [comment]
Thank you @martinezmj for replying quick. The function that i needed was resetViewer() which works fine, but the problem is I want to load series and how I am going to that I have no idea. The series of which I am talking about looks like this: 
![ds](https://cloud.githubusercontent.com/assets/5921992/21047048/9ca11c58-be29-11e6-8982-f002877244b2.PNG)

This series is saved in a global variable array named "window.customseriesMap". It looks like this in console:
![s1](https://cloud.githubusercontent.com/assets/5921992/21047100/df954412-be29-11e6-9635-98bcdd5eed5b.PNG)

Here are few more pictures which shows how the array looks in console when it is further expanded.
![s2](https://cloud.githubusercontent.com/assets/5921992/21047228/89cce4bc-be2a-11e6-8c21-1951c21f0d6f.PNG)
![s3](https://cloud.githubusercontent.com/assets/5921992/21047229/89cdb298-be2a-11e6-840a-57e9f35381ef.PNG)

**Comment by rii-mango** [comment]
Looks like this has been resolved.
