### ISSUE TITLE
webkitImageSmoothingEnabled decremented

### ISSUE THREAD

**Issue by FredLoney** [rii-mango/Papaya#78]
Running Papaya in Chrome Version 54.0.2840.98 on Mac OS X 10.11.6 results in the following console log message:

> papaya.js:21590'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated and will be removed in M55, around November 2016. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead. See https://www.chromestatus.com/features/5639849247768576 for more details.

This can be addressed by removing the src/js/viewer/viewer.js `this.context.webkitImageSmoothingEnabled` assignments. However, perhaps the assignment should be retained with a browser version check, depending on the Papaya browser compatibility requirements.

**Comment by rii-mango** [comment]
They enabled `imageSmoothingEnabled` in 2013, so it's probably safe to finally remove `webkitImageSmoothingEnabled`.  It's gone.  Thanks!
