### ISSUE TITLE
Destroy papaya instances

### ISSUE THREAD

**Issue by okrad** [rii-mango/Papaya#81]
Hi, is there a way to cleanly destroy (remove event listeners, free up used memory) an instance of papaya? 

Thanks

**Comment by rii-mango** [comment]
The closest thing currently is `papaya.viewer.Viewer.prototype.resetViewer()` in viewer.js.  This will remove the event listeners and the image data.

Also see `papaya.Container.prototype.reset()` in main.js as well as the use of `papaya.Container.resetViewer()` in main.js.
