### ISSUE TITLE
Bad reading for injected CT and X-ray angiography

### ISSUE THREAD

**Issue by FredChamp** [rii-mango/Papaya#82]
Hi,
I tried to open several CT Angiography and X-Ray angiography but it seems papaya doesn't support these DICOM types.

For CT, I have the following result:

![pa1](https://cloud.githubusercontent.com/assets/2893494/21890876/17612bc0-d8d0-11e6-8507-bf2476843f42.png)

For the X-Ray angiography, the following error:
```
Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
    at Object.b.isNIFTI1 (papaya.js:928)
    at Object.b.isNIFTI (papaya.js:929)
    at Function.papaya.volume.nifti.HeaderNIFTI.isThisFormat (papaya.js:1303)
    at papaya.volume.Header.findHeaderType (papaya.js:1277)
    at papaya.volume.Header.readHeaderData (papaya.js:1278)
    at papaya.volume.Volume.finishedReadData (papaya.js:1416)
    at papaya.js:1415
```

There is a link to download data I used: https://we.tl/zpIdhPW8EZ

Best regards,
Fred

**Comment by martinezmj** [comment]
Thanks for reporting this.  Both issues were fixed.  The second issue required both a code fix as well as a new parameter when setting up the viewer.  You need to tell it what files to ignore, when reading a DICOM folder.  By default it will ignore dot files, but you can also now specify other regex patterns to ignore.  In your case, add this before loading the viewer:

```papaya.Container.ignorePatterns.push(/.*ini/);```

**Comment by FredChamp** [comment]
Thank you for this quick fix! It works well now and sorry for the .ini thing I may have checked my DICOM folder. 

Best regards,
Frédéric
