### ISSUE TITLE
How to hide the two right parts of viewer and show only main one?

### ISSUE THREAD

**Issue by slesarevns** [rii-mango/Papaya#84]
Hi, everyone!
How to hide the two right parts of viewer and show only main one?

Thanks in advance

**Comment by martinezmj** [comment]
See the 'orthogonal' and 'mainView' parameters: https://github.com/rii-mango/Papaya/wiki/Configuration#ui-parameters

**Comment by amir201808** [comment]
Hello @martinezmj 

Are there any ways I can show all 3 views as square and show them horizontally or vertically.

Please suggest me.
