### ISSUE TITLE
Specify a file path in params

### ISSUE THREAD

**Issue by waelmassarani** [rii-mango/Papaya#85]
Hello. I am trying to use the "params["images"]" to reference an image. How can I specify a file path for that? The only available options are only a relative path within the project or through http. The problem here is that specifying a path within the application is causing a problem since the application doesn't see the added files after deployment. How can I go about that?

Also, Could you please send me full documentation about the Papaya viewer? I am currently very dependent on it in an important project.

**Comment by martinezmj** [comment]
Are you trying to give it a path local to the user's computer?  You won't be able to do that, JavaScript won't let you see the user's file system.  If you can't do it over HTTP, then you have a couple of choice.

1) If you can create a file dialog (e.g., `<input type="file">`) and get File references, then you can specify it as: `params["files"] = [myFile1, myFile2];`

2) Or else, you'd need to Base64 encode the files.  In which case you can use `params["encodedImages"] = [myEnocdedFileVar];`.  In this case, you might find [Papaya-Builder](https://github.com/rii-mango/Papaya-Builder) helpful.  There is a version of it in the root directory of Papaya.

Both of these options are talked about in this section of the Wiki: https://github.com/rii-mango/Papaya/wiki/Configuration#images

3) Alternatively, in whatever thing you're doing, maybe you can embed a lightweight HTTP server and just serve the files for local use.

All the documentation can be found here in the Wiki: https://github.com/rii-mango/Papaya/wiki

**Comment by jgardus1** [comment]
Hello,

Regarding method #2 above, is any particular formatting needed when passing the Base64 encoded data into the JavaScript "params" array? 

I'm converting a nii.gz file to Base64 and I replicated the Java "encodeImageFile" method in Papaya-Builder's Utilities.java file. But when I pass the Base64 string to Papaya in my HTML template, I receive an Uncaught TypeError (stack trace below). I've also tried prepending the Base64 string with "data:application/x-gzip;base64," to no avail. 

Any advice you can provide would be much appreciated

Thanks,

John

------------------
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Function.papaya.volume.nifti.HeaderNIFTI.isThisFormat (papaya.js:518)
    at papaya.volume.Header.findHeaderType (papaya.js:492)
    at papaya.volume.Header.readHeaderData (papaya.js:493)
    at papaya.volume.Volume.finishedReadData (papaya.js:635)
    at papaya.js:634

**Comment by martinezmj** [comment]
@jgardus1 My guess is your encoding is fine, but it just can't find the encoded image data for some reason.  In the project look at src/js/data/sample-image.js as an example encoding of tests/data/sample_image.nii.gz.  See tests/debug_local.html for example usage.
