### ISSUE TITLE
How I can change DICOM images in params[images]=[["data/series1image1","data/series1image2"]] after first Init without reload totally all page? 

### ISSUE THREAD

**Issue by slesarevns** [rii-mango/Papaya#87]
Hello, everyone!

How I can change DICOM images in params[images]=[["data/series1image1", "data/series1image2"]] after first init?  For the first init I don't have correct date and use params[images]=[["data/series1image1", "data/series1image2"]]  for example, after for some event (button click), I send xhrrequest for new data (I don't won't reload totally all page), when I make papaya.Container.resetViewer(0, params) with new params[image] I don't have correct result (papaya viewer with new DICOM images and correct render) its still old data rendered

Thanks in advance

**Comment by slesarevns** [comment]
We can dynamically create a container papaya.Container.addViewer("myDivId", myParams)

**Comment by cynde** [comment]
hi @s-inshiy , does papaya.Container.addViewer("myDivId", myParams) not reloading the entire viewer?
