### ISSUE TITLE
React JS and Papaya

### ISSUE THREAD

**Issue by Crisnil** [rii-mango/Papaya#90]
Hi how can papaya integrated with reactjs? it always says "papaya requires javascript"
then i try the iframe. how to pass params from react component to papaya viewer?

**Comment by martinezmj** [comment]
I don't have experience with ReactJS, but since you are getting the "Papaya requires JavaScript" message, this suggests that `papaya.Container.startPapaya()` is not being called.  My guess is that since this is set to be called in the window load event, that may not be compatible with ReactJS.

Try calling `papaya.Container.startPapaya()` somewhere in your code, I think that should fix the issue.

You may also find these other calls helpful: https://github.com/rii-mango/Papaya/wiki/API

**Comment by Crisnil** [comment]
thanks, that actually works calling papaya.Container.startPapaya(); im on to my next goal to send params in the compnent

**Comment by pradeepism04** [comment]
@Crisnil Have you build it in react ??

**Comment by Crisnil** [comment]
Hi, I had used papaya as plain javascript and run in reactjs as one
component. I just test it and load some static dicom image and able to load
the images. I will try to look at it again and share the code with you.

**Comment by Crisnil** [comment]
please see sample code

import React from "react";

import '~/src/components/modality/components/papaya.css'
import { Row, Col, Grid } from 'react-bootstrap'

class PapayaView extends React.Component{

    loadpick =(e)=>{
        var params = [];
        params["showOrientation"] = true;
        params["expandable"] = true;
        params["showOrientation"] = true;
        params["worldSpace"] = true;
        params["showRuler"] = true;
        params["kioskMode"]=true;
        params["showControls"]=true;
        params["showControlBar"]=true;
        params["images"]=[["/papaya/sample/brain_001.dcm",
            "/papaya/sample/brain_002.dcm",
            "/papaya/sample/brain_003.dcm",
            "/papaya/sample/brain_004.dcm",
            "/papaya/sample/brain_005.dcm",
            "/papaya/sample/brain_006.dcm",
            "/papaya/sample/brain_007.dcm",
            "/papaya/sample/brain_008.dcm",
            "/papaya/sample/brain_009.dcm",
            "/papaya/sample/brain_010.dcm",
            "/papaya/sample/brain_011.dcm",
            "/papaya/sample/brain_012.dcm",
            "/papaya/sample/brain_013.dcm",
            "/papaya/sample/brain_014.dcm",
            "/papaya/sample/brain_015.dcm",
            "/papaya/sample/brain_016.dcm",
            "/papaya/sample/brain_017.dcm",
            "/papaya/sample/brain_018.dcm",
            "/papaya/sample/brain_020.dcm",
            "/papaya/sample/brain_019.dcm"
        ]];
        console.log("button was click",params);
        papaya.Container.addViewer("viewcontent", params);
        papaya.Container.resetViewer(0, params);
        papaya.Container.addImage(0, params["images"][0]);

    };



    render(){

        var load = require('load-script');


        load ('/papaya/papaya.js?build=1422', function (err, script){
            if (err) {
                console.log("not loaded");
            }
            else {
                console.log(script.src);// Prints 'foo'.js'
                papaya.Container.startPapaya();
            }
        });


        return(
                 <Row>
                     <Col md={12} >
                        <Row>
                            <Col xs={12} md={2} >
                                <button
onClick={this.loadpick}>ShowViewer</button>
                            </Col>
                            <Col xs={12} md={10} >
                            <div id="viewcontent" data-params="params"></div>
                            </Col>
                        </Row>
                     </Col>
                </Row>

        )
    }
}
export default PapayaView;

**Comment by pradeepism04** [comment]
@Crisnil  thanks for reply, still it's saying papaya script required, 
once i refresh the page  script was loaded on index.html page 
and also saying   **Line 88:5:  'papaya' is not defined  no-undef**

**Comment by Crisnil** [comment]
take note of this

 var load = require('load-script');


        load ('/papaya/papaya.js?build=1422', function (err, script){
            if (err) {
                console.log("not loaded");
            }
            else {
                console.log(script.src);// Prints 'foo'.js'
                papaya.Container.startPapaya();
            }
        });

**Comment by pradeepism04** [comment]
var load = require("load-script");

    load("papaya.js", function(err, script) {
      if (err) {
        console.log("not loaded");
      } else {
        console.log(script.src); // Prints 'foo'.js'
        // console.log("papaya", script, papaya);
        papaya.Container.startPapaya();**----->Getting error here** 
      }
    });

papaya.js store at  component location 
and but not able to get the papaya.Container 
And getting the same error   **'papaya' is not defined  no-undef**

**Comment by Crisnil** [comment]
Did you add load-script in npm?

**Comment by pradeepism04** [comment]
@Crisnil  Yes

**Comment by Crisnil** [comment]
I think I provided you all with what have done. Maybe you do solve and
share your solution.

**Comment by arindas** [comment]
Here's a solution, complete with react functional components and react hooks: https://github.com/arindas/papaya-react

**Comment by Edwin18** [comment]
I also struggled with `papaya` and did this, perhaps it will be useful to someone. 

I splited in to 2 files:
1. `papaya` configuration file
2. React Functional Component

I did in this way cuz we have SPA + i use another viewer [niivue](https://github.com/niivue/niivue) so basicly user can choose viewer + it should rerender/update when we change patient without any reload

### `papaya` configuration file
```ts
// eslint-disable-next-line import/no-anonymous-default-export
export default (visitId: number) => {
  const setViewAngle = (an: number) => {
    // prettier-ignore
    window.papayaContainers[0].viewer.surfaceView.mouseRotCurrent = [
      -Math.cos(an),         0, Math.sin(an),          0,
       Math.sin(an),         0, Math.cos(an),          0,
                  0,         1,            0,          0,
                  0,         0,            0,          1,
    ];
  };
  const setFrameRotation = () => {
    setViewAngle(((Date.now() / 100) % 360) * (3.1415 / 180));
    window.papayaContainers[0].viewer.surfaceView.draw();
    window.papayaContainers[0].viewer.drawViewer();
  };
  const toggleAnimRotating = () => {
    if (window.papayaContainers[0].viewer.anim_rotating != null) {
      clearInterval(window.papayaContainers[0].viewer.anim_rotating);
      window.papayaContainers[0].viewer.anim_rotating = null;
    } else {
      window.papayaContainers[0].viewer.anim_rotating = setInterval(setFrameRotation, 70);
    }
  };

  window.params = {
    showControlBar: false,
    kioskMode: true,
    mainView: 'coronal',
    fullScreenPadding: true,
    showOrientation: false,
    orthogonalTall: false,
    radiological: true,
    smoothDisplay: true,
    worldSpace: true,
    ignoreNiftiTransforms: false,
    images: [
      window.api.getMriObjects('main_mri', visitId),
      window.api.getMriObjects('hippo_masks', visitId),
    ],
    surfaces: [
      window.api.getMriObjects('head.surf.gii', visitId),
      window.api.getMriObjects('hippo_mask.surf.gii', visitId),
    ],
    loadingComplete: () => {
      window.papayaContainers[0].viewer.surfaceView.backgroundColor = [0.0, 0.0, 0.0];
      // prettier-ignore
      window.papayaContainers[0].viewer.surfaceView.mouseRotCurrent = [
        -0.682,         0.105,         -0.724,         0,
        -0.726,        -0.204,          0.656,         0,
        -0.078,         0.973,          0.215,         0,
             0,             0,              0,         1,
      ];
      window.papayaContainers[0].viewer.surfaceView.showSurfacePlanes = false;
      window.papaya.Container.showImage(0, 0);
      toggleAnimRotating();
    },

    // Specific file configuration
    main_mri: { interpolation: false, min: 0, max: 170 },
    hippo_masks: { min: 192, max: 270, lut: 'Red Overlay', alpha: 0.7 },
    'head.surf.gii': { alpha: 0.6 },
    'hippo_mask.surf.gii': { color: [1, 0.9, 0.2], alpha: 1 },
  };
};
```

### React Functional Component
```TSX
import { TGlobalDataSet } from '@ts-types/types';
import Papaya from '@ts/brain-viewer/papaya';
import React, { FC, useEffect } from 'react';

type TBrainViewerPapaya = {
  id: number;
};

const BrainViewerPapaya: FC<TGlobalDataSet & TBrainViewerPapaya> = ({ id }) => {
  useEffect(() => {
    const papayaScript = document.createElement('script');

    papayaScript.src = '/static/my-page/js/papaya.js';
    papayaScript.onload = () => {
      Papaya(id);
      window.papaya.Container.startPapaya();
    };

    document.body.appendChild(papayaScript);

    return () => {
      // Clear rotation interval
      if (window.papayaContainers[0]?.viewer?.anim_rotating) clearInterval(window.papayaContainers[0].viewer.anim_rotating);
      // Clear all previous listeners
      // TODO: Find all other events and remove them otherwise its leak of memory!
      window.removeEventListener('resize', window.papaya.Container.resizePapaya, !1);
      window.removeEventListener('orientationchange', window.papaya.Container.reorientPapaya, !1);
      window.removeEventListener('load', window.papaya.Container.startPapaya, !1);
      // Remove script
      document.body.removeChild(papayaScript);
      // Clear all variable
      window.params = undefined;
      window.papayaContainers = undefined;
      window.papaya = undefined;
    };
  }, [id]);

  return <div className='home-brain-viewer-papaya papaya' data-params='params' />;
};

export default BrainViewerPapaya;

```
