### ISSUE TITLE
More function for papaya?

### ISSUE THREAD

**Issue by zhan2016** [rii-mango/Papaya#91]
Hi, your work is amazing. 
1 Can we get more function, For example zoom,pan,measurement, CT Probe?
2 Can we get more Viewer, For example a VR/VE visual, a MIP visual?
Is it possible to develop these functions/visuals based on your lib?
if ansewer is yes,  how to do this?Any way to achieve these goals?
Thank you very much!

**Comment by rii-mango** [comment]
Thanks!  A lot of your answers can be found here: https://github.com/rii-mango/Papaya/wiki/User-Interface-Features

There is already support for zoom and pan as well as a line measurement.  The other functions would need to be added.  The [context manager](https://github.com/rii-mango/Papaya/wiki/How-To-Make-a-Context-Manager) is one example of creating something like a "plugin" for papaya.  The [API](https://github.com/rii-mango/Papaya/wiki/API) is also a good place to start.

I'm happy to merge in any new features if they are useful for a general populations of users.   Feel free to let me know if you have any questions.
