### ISSUE TITLE
What Overlay function based?

### ISSUE THREAD

**Issue by tymiao1220** [rii-mango/Papaya#94]
Hi papaya developer,

I am using that nice software in my project, but I got some issue about overlay function.
The issue is that, if I use the slices in the some series(No.1), they can overlay each other pretty well, whereas if I use different series' slice(No.2 let's say) overlay does not work anymore, then I am thinking overlay might be identified by some header params? so I tried to change the No.2's series description header, it still does not work. Single image display works fine for both, just cannot overlay each other.
The reason I am asking is because eventually, I want to use this to overlay some processed dicom image result(from itk/vtk, eg. detected roundness result) with original dicom image, and that processed result could be dicom type with or without same header info.
So I am wondering what header ( or something else) that papaya overlay function based on?

Best wishes,
Adam

**Comment by martinezmj** [comment]
The images are aligned based on the header information `papaya.volume.dicom.HeaderDICOM.prototype.getOrigin()` and the `papaya.volume.dicom.HeaderDICOM.prototype.getVoxelDimensions()`.

Do the images that you want to overlay have the same image and voxel dimensions?  Or are you trying to align them based on a certain location (e.g., origin pixel)?

**Comment by tymiao1220** [comment]
Thank @martinezmj! I go over all code and realized that the result images header are destroy which cause papaya using default parameters for these no header images, so original image (with correct header like origin/spacing as you mentioned) will no match with them.
