### ISSUE TITLE
loadBaseImage Error: This format is not recognized!

### ISSUE THREAD

**Issue by joshy** [rii-mango/Papaya#95]
Hi, 

I have a small Python Flask application which returns CT images in nifti format. A request url looks like this
`image_data?acc_number=123456789&image_type=ct`

If I then try to load that url with 
`papayaContainers[0].viewer.loadBaseImage(["image_data?acc_number=123456789&image_type=ct"], true)` it fails with

```
Error: This format is not recognized!
    at papaya.volume.Header.readHeaderData (packed.js?5b9f2575:formatted:34082)
    at papaya.volume.Volume.finishedReadData (packed.js?5b9f2575:formatted:35586)
    at packed.js?5b9f2575:formatted:35574
```

Download the image and then dropping the image works. So the image should be fine. It downloads as `ct.nii.gz`.

My guess is that fileName is empty and therefore it is not recognised as a supported format. Is there a way I can set the file name?

Thanks for your time,
Joshy

**Comment by martinezmj** [comment]
Thanks for reporting this.  The issue was that it wasn't recognizing that it was compressed without the filename.  This has been fixed.

**Comment by joshy** [comment]
Thanks a lot. Fixed with https://github.com/rii-mango/Papaya/releases/tag/build-1427
