### ISSUE TITLE
Incompatible with bootstrap grid layout system

### ISSUE THREAD

**Issue by ihier** [rii-mango/Papaya#96]
The bootstrap grid system is used quite often in html to create flexible layouts. It is unfortunate that papaya is not compatible with this system. When the mouse is right clicked on the viewer or the window-level icon is clicked, the positions of papaya viewer, buttons and window-level adjustment panels are not correct. Is there any way to fix this issue?

See code below for recreation of the aforementioned problem. 
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
	<head>
		<link rel="stylesheet" type="text/css" href="papaya.css" /> 
		<script type="text/javascript" src="papaya.js"></script>  
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<title>Papaya Viewer</title>
		<script type="text/javascript">
			var params = [];
			params["images"] = ["test.nii"];
		</script>		
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-8"></div>
				<div class="col-lg-4"><div class="papaya" data-params="params"></div></div>
			</div>
		</div>
	</body>
</html>
```
![papaya_right_click](https://cloud.githubusercontent.com/assets/28893229/26350317/091182a0-3fb3-11e7-9a15-e1254d6734c1.jpg)

**Comment by martinezmj** [comment]
Should be fixed now.  Give it a try.  I also added your example as tests/debug_server_bootstrap.html.  Thanks for reporting this.
