### ISSUE TITLE
papaya.Container.addImage() does not seem to work

### ISSUE THREAD

**Issue by hotpixelgroup** [rii-mango/Papaya#97]
When newing up a new Papaya viewer dynamically via the startPapaya method, the addImage method  does not work.

 `papaya.Container.startPapaya();` => properly instantiates viewer
 `papaya.Container.addImage(0, 'image ref here');` => does not add image to viewer

**Comment by martinezmj** [comment]
`addImage()` is intended to add an second image onto an already instantiated viewer.  What you want is `addViewer()`.

`papaya.Container.addViewer("myDiv", params);`

A bit more info here: https://github.com/rii-mango/Papaya/wiki/API#api-methods

**Comment by hotpixelgroup** [comment]
Gotcha. Thank you!
