### ISSUE TITLE
4D image visualisation

### ISSUE THREAD

**Issue by renardfe** [rii-mango/Papaya#98]
Hi, your work is amazing.

I would like to visualise 4D images. I can read the 4D images and see that I am in the first image (1 of 62 written in front of the viewer). But I cannot access the other images (2, 3 etc... of 62).

The command provided in the documention doesn't work for me.
(<) or (,) Decrement the timepoint.
(>) or (.) Increment the timepoint.

My image is Diffusion MRI. Is it an issue?

Thanks!!

**Comment by martinezmj** [comment]
Hi. Sorry for the late reply.  It sounds like you are using it correctly.  I just tested this feature and I can't find any issues with it.  Two things to try:

1) Maybe it is simply a keyboard focus issue.  Try clicking in the image somewhere first, then try the < > keys to move through the series.

2) Try setting `showControlBar`.  If it's a series, you should see buttons to navigate through it.

`params['showControlBar'] = true;`
<img width="615" alt="screen shot 2017-06-11 at 4 01 59 pm" src="https://user-images.githubusercontent.com/20823434/27014486-8543cd04-4ebf-11e7-860a-1c83b8fec90c.png">

Let me know if you still can't get this to work.
